import { z } from "zod";
import type { Prisma } from "@/generated/prisma/client";
import { prisma } from "@/lib/prisma";
import type { PlatformRequest } from "@/lib/platform-auth";
import { CAMPAIGN_STATUSES, CONTENT_CHANNELS } from "@/lib/marketing-rules";

const prohibitedSensitiveContent = /\b(patient|date of birth|dob|personal health number|phn|medical record|clinical note)\b/i;
const safeText = (min: number, max: number) => z.string().trim().min(min).max(max).refine((value) => !prohibitedSensitiveContent.test(value), { message: "Do not include patient or clinical-record information." });
const optionalText = (max: number) => z.string().trim().max(max).nullable().transform((value) => value || null);
const optionalCount = z.number().int().nonnegative().nullable();

const campaignFields = {
  name: safeText(3, 160), sourceKey: z.string().trim().regex(/^[a-z0-9][a-z0-9_-]{2,79}$/), objective: safeText(3, 240),
  targetSegment: safeText(3, 160), channel: z.enum(CONTENT_CHANNELS), ownerUserId: optionalText(128), contentAssetId: optionalText(128),
  landingPath: z.string().trim().regex(/^\/[A-Za-z0-9/_-]*$/).max(180).nullable().transform((value) => value || null),
  utmSource: optionalText(100), utmMedium: optionalText(100), utmCampaign: optionalText(100), plannedStartAt: z.string().datetime().nullable(),
  plannedEndAt: z.string().datetime().nullable(), reviewAt: z.string().datetime().nullable(), externalApprovalReference: optionalText(240),
  budgetApprovalReference: optionalText(240), approvedBudgetCents: z.number().int().nonnegative().nullable(), recordedSpendCents: z.number().int().nonnegative().nullable(),
};
export const createCampaignSchema = z.object({ mutationId: z.string().uuid(), ...campaignFields }).strict().superRefine(dateAndBudgetRules);
export const campaignMutationSchema = z.object({ expectedVersion: z.number().int().nonnegative(), mutationId: z.string().uuid(), status: z.enum(CAMPAIGN_STATUSES), ...campaignFields }).strict().superRefine(dateAndBudgetRules);

function dateAndBudgetRules(value: { plannedStartAt: string | null; plannedEndAt: string | null; budgetApprovalReference: string | null; approvedBudgetCents: number | null; recordedSpendCents: number | null }, context: z.RefinementCtx) {
  if (value.plannedStartAt && value.plannedEndAt && value.plannedEndAt <= value.plannedStartAt) context.addIssue({ code: "custom", path: ["plannedEndAt"], message: "Campaign end must be after its start." });
  if ((value.approvedBudgetCents !== null || value.recordedSpendCents !== null) && !value.budgetApprovalReference) context.addIssue({ code: "custom", path: ["budgetApprovalReference"], message: "Budget or spend records require an approval reference." });
}

export const attributionSnapshotSchema = z.object({
  mutationId: z.string().uuid(), sourceReference: safeText(3, 240), periodStartAt: z.string().datetime(), periodEndAt: z.string().datetime(),
  visitCount: optionalCount, leadCount: optionalCount, qualifiedCount: optionalCount, demoCount: optionalCount, pilotCount: optionalCount,
  clientCount: optionalCount, revenueCents: optionalCount, currency: z.literal("CAD"), notes: optionalText(500),
}).strict().superRefine((value, context) => {
  if (value.periodEndAt <= value.periodStartAt) context.addIssue({ code: "custom", path: ["periodEndAt"], message: "Period end must be after its start." });
  const metrics = [value.visitCount, value.leadCount, value.qualifiedCount, value.demoCount, value.pilotCount, value.clientCount, value.revenueCents];
  if (metrics.every((metric) => metric === null)) context.addIssue({ code: "custom", path: ["visitCount"], message: "Record at least one measured metric; leave unknown values blank." });
  const funnel = [value.visitCount, value.leadCount, value.qualifiedCount, value.demoCount, value.pilotCount, value.clientCount];
  for (let index = 1; index < funnel.length; index += 1) { const prior = funnel[index - 1]; const current = funnel[index]; if (prior !== null && current !== null && current > prior) context.addIssue({ code: "custom", path: [["visitCount", "leadCount", "qualifiedCount", "demoCount", "pilotCount", "clientCount"][index]], message: "Downstream funnel counts cannot exceed the preceding measured stage." }); }
  if (value.notes && prohibitedSensitiveContent.test(value.notes)) context.addIssue({ code: "custom", path: ["notes"], message: "Do not include patient or clinical-record information." });
});

type CampaignCreate = z.infer<typeof createCampaignSchema>; type CampaignMutation = z.infer<typeof campaignMutationSchema>; type SnapshotInput = z.infer<typeof attributionSnapshotSchema>;
export class CampaignRegistryError extends Error { constructor(public readonly code: "record_not_found" | "invalid_owner" | "asset_not_approved" | "activation_requires_approval" | "activation_requires_owner" | "no_changes" | "version_conflict" | "idempotency_conflict", message: string) { super(message); } }

async function replay(mutationId: string, action: string, targetType: string) { const audit = await prisma.platformAuditEvent.findUnique({ where: { requestId: mutationId }, select: { action: true, targetType: true, targetId: true } }); if (!audit) return null; if (audit.action !== action || audit.targetType !== targetType || !audit.targetId) throw new CampaignRegistryError("idempotency_conflict", "Mutation id belongs to another operation."); return audit.targetId; }
async function validate(input: CampaignCreate | CampaignMutation, status: string, operator: PlatformRequest) { if (input.ownerUserId) { const owner = await prisma.platformUserRole.findFirst({ where: { userId: input.ownerUserId, active: true, role: { in: ["owner", "marketing"] } }, select: { id: true } }); if (!owner) throw new CampaignRegistryError("invalid_owner", "Campaign owner must be an active owner or marketing operator."); } if (["ready", "observed_active"].includes(status)) { if (!input.contentAssetId) throw new CampaignRegistryError("asset_not_approved", "Ready campaigns require an approved content asset."); const asset = await prisma.contentAsset.findUnique({ where: { id: input.contentAssetId }, select: { status: true, channel: true } }); if (!asset || asset.status !== "approved" || asset.channel !== input.channel) throw new CampaignRegistryError("asset_not_approved", "Content asset must be approved for this campaign channel."); } if (status === "observed_active") { if (operator.role !== "owner") throw new CampaignRegistryError("activation_requires_owner", "Only the accountable owner can record an externally activated campaign."); if (!input.externalApprovalReference) throw new CampaignRegistryError("activation_requires_approval", "Observed external activation requires its approval reference."); } }
async function history(tx: Prisma.TransactionClient, args: { recordId: string; action: string; mutationId: string; fields: string[]; operator: PlatformRequest }) { await tx.marketingActivity.create({ data: { recordType: "campaign", recordId: args.recordId, actorUserId: args.operator.userId, actorRole: args.operator.role, kind: args.action, mutationId: args.mutationId, changesJson: JSON.stringify({ changedFields: args.fields }) } }); await tx.platformAuditEvent.create({ data: { actorUserId: args.operator.userId, actorRole: args.operator.role, action: args.action, targetType: "campaign", targetId: args.recordId, requestId: args.mutationId, metadataJson: JSON.stringify({ changedFields: args.fields }) } }); }
function data(input: CampaignCreate | CampaignMutation) { return { name: input.name, sourceKey: input.sourceKey, objective: input.objective, targetSegment: input.targetSegment, channel: input.channel, ownerUserId: input.ownerUserId, contentAssetId: input.contentAssetId, landingPath: input.landingPath, utmSource: input.utmSource, utmMedium: input.utmMedium, utmCampaign: input.utmCampaign, plannedStartAt: input.plannedStartAt ? new Date(input.plannedStartAt) : null, plannedEndAt: input.plannedEndAt ? new Date(input.plannedEndAt) : null, reviewAt: input.reviewAt ? new Date(input.reviewAt) : null, externalApprovalReference: input.externalApprovalReference, budgetApprovalReference: input.budgetApprovalReference, approvedBudgetCents: input.approvedBudgetCents, recordedSpendCents: input.recordedSpendCents }; }
export async function createCampaign(input: CampaignCreate, operator: PlatformRequest) { const id = await replay(input.mutationId, "campaign_created", "campaign"); if (id) return prisma.campaign.findUniqueOrThrow({ where: { id } }); await validate(input, "planning", operator); return prisma.$transaction(async (tx) => { const campaign = await tx.campaign.create({ data: data(input) }); await history(tx, { recordId: campaign.id, action: "campaign_created", mutationId: input.mutationId, fields: Object.keys(data(input)), operator }); return campaign; }); }
export async function updateCampaign(id: string, input: CampaignMutation, operator: PlatformRequest) { const replayId = await replay(input.mutationId, "campaign_updated", "campaign"); if (replayId) { if (replayId !== id) throw new CampaignRegistryError("idempotency_conflict", "Mutation id belongs to another campaign."); return prisma.campaign.findUniqueOrThrow({ where: { id } }); } const prior = await prisma.campaign.findUnique({ where: { id } }); if (!prior) throw new CampaignRegistryError("record_not_found", "Campaign not found."); await validate(input, input.status, operator); const next = { ...data(input), status: input.status }; const fields = Object.keys(next).filter((key) => String(prior[key as keyof typeof prior] ?? "") !== String(next[key as keyof typeof next] ?? "")); if (!fields.length) throw new CampaignRegistryError("no_changes", "No campaign changes were supplied."); return prisma.$transaction(async (tx) => { const result = await tx.campaign.updateMany({ where: { id, version: input.expectedVersion }, data: { ...next, version: { increment: 1 } } }); if (result.count !== 1) throw new CampaignRegistryError("version_conflict", "Campaign changed after this form was loaded."); await history(tx, { recordId: id, action: "campaign_updated", mutationId: input.mutationId, fields, operator }); return tx.campaign.findUniqueOrThrow({ where: { id } }); }); }
export async function recordAttributionSnapshot(campaignId: string, input: SnapshotInput, operator: PlatformRequest) { const existing = await prisma.campaignAttributionSnapshot.findUnique({ where: { mutationId: input.mutationId } }); if (existing) { if (existing.campaignId !== campaignId) throw new CampaignRegistryError("idempotency_conflict", "Mutation id belongs to another campaign."); return existing; } if (!(await prisma.campaign.findUnique({ where: { id: campaignId }, select: { id: true } }))) throw new CampaignRegistryError("record_not_found", "Campaign not found."); return prisma.$transaction(async (tx) => { const snapshot = await tx.campaignAttributionSnapshot.create({ data: { campaignId, mutationId: input.mutationId, sourceReference: input.sourceReference, periodStartAt: new Date(input.periodStartAt), periodEndAt: new Date(input.periodEndAt), visitCount: input.visitCount, leadCount: input.leadCount, qualifiedCount: input.qualifiedCount, demoCount: input.demoCount, pilotCount: input.pilotCount, clientCount: input.clientCount, revenueCents: input.revenueCents, currency: input.currency, notes: input.notes, recordedByUserId: operator.userId, recordedByRole: operator.role } }); await tx.platformAuditEvent.create({ data: { actorUserId: operator.userId, actorRole: operator.role, action: "campaign_attribution_recorded", targetType: "campaign", targetId: campaignId, requestId: input.mutationId, metadataJson: JSON.stringify({ snapshotId: snapshot.id, knownMetrics: ["visitCount", "leadCount", "qualifiedCount", "demoCount", "pilotCount", "clientCount", "revenueCents"].filter((key) => input[key as keyof SnapshotInput] !== null) }) } }); return snapshot; }); }
