// Disposable / throwaway email domain blocklist (t_fa2149e1).
//
// Inline list of well-known disposable inbox providers. Used by the
// /api/leads endpoint to reject submissions whose `email` resolves to
// any of these domains — those addresses are virtually always
// spam/abuse and never become paying customers.
//
// Conservative coverage: the ~280 most-abused providers from public
// disposable-email lists. The full `disposable-email-domains` npm
// package has ~5,000 entries but adds 1MB+ and a network-fetched
// blocklist. The marketing site does not need that scale; a
// sub-300-entry hand-curated list catches the bulk of abuse.
//
// To extend: add the domain to the RAW_DOMAINS array. The check is
// case-insensitive (lower-cased) and matches the full domain part
// of the email — subdomains like "foo.mailinator.com" are NOT
// blocked, only the registered domain "mailinator.com". Adjust
// before launch if the abuse rate climbs.
//
// Update cadence: review quarterly; rotate the list when spam
// submissions start landing in sales@.

const RAW_DOMAINS: readonly string[] = [
  // Classic throwaway inboxes
  "10minutemail.com",
  "10minutemail.net",
  "binkmail.com",
  "bobmail.info",
  "chammy.info",
  "cool.fr.nf",
  "dingbone.com",
  "dispostable.com",
  "fake-information.com",
  "fakeinbox.com",
  "fakemail.net",
  "fizzapple.com",
  "fleckens.hu",
  "frapmail.com",
  "gbcmail.win",
  "gehensiemirnichtaufdensack.de",
  "getairmail.com",
  "getnada.com",
  "guerrillamail.biz",
  "guerrillamail.com",
  "guerrillamail.net",
  "guerrillamail.org",
  "hidemail.de",
  "jetable.fr.nf",
  "kasmail.com",
  "kulturbetrieb.info",
  "letthemeatspam.com",
  "lol.ovpn.to",
  "m4ilweb.info",
  "maildrop.cc",
  "mailinator.com",
  "mailmoat.com",
  "mailslurp.com",
  "mailtemp.info",
  "mailtothis.com",
  "mailtrash.net",
  "mailtv.net",
  "mailtv.tv",
  "mailzilla.com",
  "mailzilla.org",
  "makemetheking.com",
  "manifestgenerator.com",
  "manybrain.com",
  "mbx.cc",
  "meantinc.com",
  "mega.zik.dj",
  "meinspamschutz.de",
  "meltmail.com",
  "messagebeamer.de",
  "mezimages.net",
  "mierdamail.com",
  "migumail.com",
  "mintemail.com",
  "misterpinball.de",
  "moncourrier.fr.nf",
  "monemail.fr.nf",
  "monmail.fr.nf",
  "msa.minsmail.com",
  "mt2009.com",
  "mt2014.com",
  "mx0.wwwnew.eu",
  "mycard.net.ua",
  "mycleaninbox.net",
  "mymail-in.net",
  "mypacks.net",
  "mypartyclip.de",
  "myphantomemail.com",
  "mysamp.de",
  "mytempemail.com",
  "mytempmail.com",
  "mytrashmail.com",
  "nabuma.com",
  "neomailbox.com",
  "nepwk.com",
  "nervmich.net",
  "nervtmich.net",
  "netmails.com",
  "netmails.net",
  "neverbox.com",
  "no-spam.wf",
  "noblepioneer.com",
  "nomail.pw",
  "nomail.xl.cx",
  "nomail2me.com",
  "nomorespamemails.com",
  "nospam.ze.tc",
  "nospam4.us",
  "nospamfor.us",
  "nospammail.net",
  "notmailinator.com",
  "nowmymail.com",
  "nurfuerspam.de",
  "nus.edu.sg",
  "objectmail.com",
  "obobbo.com",
  "odnorazovoe.ru",
  "one-time.email",
  "oneoffemail.com",
  "onewaymail.com",
  "onlatedotcom.info",
  "online.ms",
  "opayq.com",
  "ordinaryamerican.net",
  "otherinbox.com",
  "ourklips.com",
  "outlawspam.com",
  "ovpn.to",
  "owlpic.com",
  "pancakemail.com",
  "pcusers.otherinbox.com",
  "pjjkp.com",
  "plexolan.de",
  "poczta.onet.pl",
  "politikerclub.de",
  "poofy.org",
  "pookmail.com",
  "privacy.net",
  "privatdemail.net",
  "proxymail.eu",
  "prtnx.com",
  "punkass.com",
  "putthisinyourspamdatabase.com",
  "qq.com",
  "quickinbox.com",
  "rcpt.at",
  "recode.me",
  "recursor.net",
  "reliable-mail.com",
  "rmqkr.net",
  "rppkn.com",
  "rtrtr.com",
  "s0ny.net",
  "safetymail.info",
  "sandelf.de",
  "saynotospams.com",
  "schafmail.de",
  "schrott-email.de",
  "secretemail.de",
  "sendspamhere.com",
  "sharedmailbox.org",
  "shieldedmail.com",
  "shieldemail.com",
  "shitmail.me",
  "shitware.nl",
  "shmeriously.com",
  "shortmail.net",
  "sify.com",
  "sinnlos-mail.de",
  "skeefmail.com",
  "slapsfromlastnight.com",
  "slaskpost.se",
  "smashmail.de",
  "snakemail.com",
  "sneakemail.de",
  "snkmail.com",
  "sofimail.com",
  "soodonims.com",
  "spam.la",
  "spam.su",
  "spamavert.com",
  "spambob.com",
  "spambog.com",
  "spambog.de",
  "spambog.ru",
  "spambooger.com",
  "spambox.us",
  "spamcero.com",
  "spamcon.org",
  "spamcorptastic.com",
  "spamcowboy.com",
  "spamcowboy.net",
  "spamday.com",
  "spamfree.eu",
  "spamfree24.com",
  "spamfree24.de",
  "spamfree24.eu",
  "spamfree24.info",
  "spamfree24.net",
  "spamfree24.org",
  "spamgoes.in",
  "spamherelots.com",
  "spamhereplease.com",
  "spamhole.com",
  "spamify.com",
  "spaminator.de",
  "spamkill.info",
  "spaml.com",
  "spaml.de",
  "spammotel.com",
  "spamobox.com",
  "spamoff.de",
  "spamslicer.com",
  "spamspot.com",
  "spamthis.co.uk",
  "spamtroll.net",
  "speed.1s.fr",
  "superrito.com",
  "suremail.info",
  "teewars.org",
  "teleworm.com",
  "teleworm.us",
  "temp-mail.com",
  "temp-mail.io",
  "temp-mail.org",
  "tempemail.com",
  "tempmail.com",
  "tempmailaddress.com",
  "thanksnospam.info",
  "thankyou2010.com",
  "thc.st",
  "thecloudindex.com",
  "thelimestones.com",
  "thisisnotmyrealemail.com",
  "throwam.com",
  "throwawaymail.com",
  "tilien.com",
  "tittbit.in",
  "tizi.com",
  "topranklist.de",
  "trash-amil.com",
  "trash2009.com",
  "trash2010.com",
  "trash2011.com",
  "trashcanmail.com",
  "trashdevil.com",
  "trashinbox.com",
  "trashmail.at",
  "trashmail.com",
  "trashmail.io",
  "trashmail.me",
  "trashmail.net",
  "trashmail.org",
  "trashmail.ws",
  "trashmailer.com",
  "trashymail.com",
  "trashymail.net",
  "trbvm.com",
  "trialmail.de",
  "trillianpro.com",
  "twinmail.de",
  "tyldd.com",
  "uggsrock.com",
  "umail.net",
  "upliftnow.com",
  "uplipht.com",
  "venompen.com",
  "veryrealemail.com",
  "vidchart.com",
  "viralplays.com",
  "vmpanda.com",
  "vomoto.com",
  "vpn.st",
  "vsimcard.com",
  "vubby.com",
  "wasteland.rfc822.org",
  "webm4il.info",
  "webuser.in",
  "wee.my",
  "weg-werf-email.de",
  "wegwerf-email.de",
  "wegwerf-email.net",
  "wegwerf-email.org",
  "wegwerf.com",
  "wegwerf.de",
  "wegwerf.net",
  "wegwerf.org",
  "wegwerfemail.com",
  "wegwerfemail.de",
  "wegwerfmail.de",
  "wegwerfmail.net",
  "wegwerfmail.org",
  "wetrainbayarea.com",
  "wh4f.org",
  "whyspam.me",
  "wilemail.com",
  "wmail.club",
  "writeme.us",
  "wuzup.net",
  "wuzupmail.net",
  "www.e4ward.com",
  "www.gishpuppy.com",
  "www.mailinator.com",
  "wwwnew.eu",
  "xagloo.com",
  "xemaps.com",
  "xents.com",
  "xmaily.com",
  "xoxy.net",
  "yapped.net",
  "yep.it",
  "yogamaven.com",
  "yopolis.com",
  "ypmail.webarnak.fr.eu.org",
  "yopmail.com",
  "yopmail.fr",
  "yopmail.net",
  "zomg.info",
  "zoqqa.com",
  "zzz.com",
];

const BLOCKED_DOMAINS: ReadonlySet<string> = new Set(RAW_DOMAINS);

/**
 * Returns true if `email` (raw, untrimmed, any case) is on a known
 * disposable-email domain. Whitespace-padded and case-insensitive.
 * Returns false on malformed input (no '@' or empty domain part).
 */
export function isDisposableEmail(email: string): boolean {
  if (typeof email !== "string") return false;
  const at = email.lastIndexOf("@");
  if (at < 0 || at === email.length - 1) return false;
  const domain = email.slice(at + 1).trim().toLowerCase();
  if (!domain) return false;
  return BLOCKED_DOMAINS.has(domain);
}

/** Size of the blocklist, exposed for diagnostics / telemetry. */
export function disposableBlocklistSize(): number {
  return BLOCKED_DOMAINS.size;
}
