#!/usr/bin/env bash
# deploy-to-vps.sh — first-time setup + redeploy for ai-billing-audit
#
# What this does
# --------------
# 1. rsyncs the project source (no node_modules, no .venv, no .git,
#    no apps/portal) to the host at /opt/projects/ai-billing-audit/
# 2. writes /opt/projects/ai-billing-audit/.env on the host with the
#    LLM provider, MiniMax key/base, postgres password, and the
#    resolved DATABASE_URL / AUDIT_TRAIL_DB
# 3. writes /etc/traefik/dynamic/routers.yml (and tls.yml) on the host
#    with a new ai-billing-audit router+service pointing at the
#    in-stack Caddy on 127.0.0.1:3018
# 4. docker compose build + up -d
# 5. smoke tests:
#    - curl http://127.0.0.1:3018/healthz on the host
#    - curl https://ai-billing-audit.ashbi.ca/healthz from the public
#      internet (waits up to 90s for the Let's Encrypt cert to issue)
#
# Idempotent: re-running does not duplicate containers or Traefik
# routes. Existing routes in routers.yml are preserved; only the
# ai-billing-audit block is rewritten.
#
# Pre-flight
# ----------
# - SSH alias 'coolify' must be configured (~/.ssh/config) and reachable.
# - The host must already have Traefik v3.2 serving :80/:443 and
#   watching /etc/traefik/dynamic (verified at deploy time).
# - DNS for ai-billing-audit.ashbi.ca must point to 187.77.26.99.
# - The MiniMax API key lives on the host at
#   /root/ai-billing-audit-secrets/minimax.env (key=MINIMAX_API_KEY).
#   The deploy script reads it but never prints the value.

set -euo pipefail

# --- Config ---
HOST="coolify"
REMOTE_DIR="/opt/projects/ai-billing-audit"
HOST_PORT="3018"
PUBLIC_HOSTNAME="ai-billing-audit.ashbi.ca"
SECRETS_FILE="/root/ai-billing-audit-secrets/minimax.env"
POSTGRES_PASSWORD_FILE="/root/ai-billing-audit-secrets/postgres.password"

# Resolve this script's own dir on the local machine.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$SCRIPT_DIR"

# --- Helpers ---
log()  { printf '[deploy %s] %s\n' "$(date +%H:%M:%S)" "$*"; }
fail() { printf '[deploy FAIL] %s\n' "$*" >&2; exit 1; }

require_local_file() {
    [ -f "$1" ] || fail "missing local file: $1"
}

# --- Pre-flight ---
require_local_file "$PROJECT_DIR/Dockerfile"
require_local_file "$PROJECT_DIR/docker-compose.yml"
require_local_file "$PROJECT_DIR/Caddyfile"
require_local_file "$PROJECT_DIR/audit_trail.sql"
require_local_file "$PROJECT_DIR/pyproject.toml"

log "preflight: ssh $HOST"
ssh -o ConnectTimeout=5 "$HOST" true || fail "ssh $HOST unreachable"

# Make sure the host has docker compose v2.
log "preflight: docker compose v2 on host"
ssh "$HOST" 'command -v docker && docker compose version' >/dev/null \
    || fail "host missing docker compose v2"

# Pull the MiniMax key from the host. Never echo it locally; build the
# .env file on the host directly so the key never transits our terminal.
ssh "$HOST" "test -f $SECRETS_FILE" \
    || fail "host missing secrets file: $SECRETS_FILE (create it with MINIMAX_API_KEY=...)"
ssh "$HOST" "test -f $POSTGRES_PASSWORD_FILE" \
    || fail "host missing postgres password file: $POSTGRES_PASSWORD_FILE (create it with the password on a single line)"

# --- Step 1: rsync source to the host ---
log "rsync source -> $HOST:$REMOTE_DIR"
ssh "$HOST" "mkdir -p $REMOTE_DIR"
rsync -az --delete \
    --exclude='.venv/' \
    --exclude='__pycache__/' \
    --exclude='.pytest_cache/' \
    --exclude='.mypy_cache/' \
    --exclude='.ruff_cache/' \
    --exclude='.git/' \
    --exclude='node_modules/' \
    --exclude='apps/' \
    --exclude='tests/' \
    --exclude='docs/' \
    --exclude='logs/' \
    --exclude='data/' \
    --exclude='artifacts/' \
    --exclude='prompts/' \
    --exclude='rules/' \
    --exclude='*.md' \
    --exclude='.DS_Store' \
    "$PROJECT_DIR/" "$HOST:$REMOTE_DIR/"

# --- Step 2: write .env on the host ---
log "write .env on host (DATABASE_URL, AUDIT_TRAIL_DB, LLM keys)"
ssh "$HOST" bash -s <<'REMOTE_ENV_EOF'
set -euo pipefail
SECRETS_FILE=/root/ai-billing-audit-secrets/minimax.env
POSTGRES_PASSWORD_FILE=/root/ai-billing-audit-secrets/postgres.password
ENV_FILE=/opt/projects/ai-billing-audit/.env

# shellcheck disable=SC1090
. "$SECRETS_FILE"
[ -n "${MINIMAX_API_KEY:-}" ] || { echo "MINIMAX_API_KEY unset in $SECRETS_FILE" >&2; exit 1; }
PG_PASSWORD="$(cat "$POSTGRES_PASSWORD_FILE")"
[ -n "$PG_PASSWORD" ] || { echo "postgres password file is empty" >&2; exit 1; }

cat > "$ENV_FILE" <<ENV
# generated by deploy-to-vps.sh — do not edit by hand
LLM_PROVIDER=minimax
MINIMAX_BASE_URL=https://api.minimax.chat/v1
MINIMAX_API_KEY=${MINIMAX_API_KEY}
DATABASE_URL=postgresql://audit:${PG_PASSWORD}@postgres:5432/ai_billing_audit
AUDIT_TRAIL_DB=postgresql://audit:${PG_PASSWORD}@postgres:5432/ai_billing_audit
POSTGRES_PASSWORD=${PG_PASSWORD}
LOG_LEVEL=INFO
ENV
chmod 600 "$ENV_FILE"
echo "wrote $ENV_FILE"
REMOTE_ENV_EOF

# --- Step 3: write Traefik dynamic router+service on the host ---
log "write Traefik router+service for $PUBLIC_HOSTNAME -> 127.0.0.1:$HOST_PORT"
ssh "$HOST" bash -s <<REMOTE_TRAEFIK_EOF
set -euo pipefail
ROUTERS=/etc/traefik/dynamic/routers.yml
TLS=/etc/traefik/dynamic/tls.yml
BACKUP_ROUTERS="\${ROUTERS}.bak.\$(date +%Y%m%d_%H%M%S)"

# Backup the current routers file before we touch it.
cp -a "\$ROUTERS" "\$BACKUP_ROUTERS"

# Idempotent insert: remove any existing ai-billing-audit router/service
# blocks, then append the new ones. python is available on the host
# (every AlmaLinux 10 box has it) and avoids heredoc-quoting hell.
python3 - <<'PYEOF'
import re, pathlib
p = pathlib.Path("/etc/traefik/dynamic/routers.yml")
src = p.read_text()

# Strip any prior ai-billing-audit router and service blocks (key:
# line at column 0, ending at the next blank line / next top-level key).
def strip_block(text, key):
    pattern = re.compile(
        rf"^  {re.escape(key)}:\n(?:    .*\n|\n)+",
        re.MULTILINE,
    )
    return pattern.sub("", text)

src = strip_block(src, "ai-billing-audit")
src = strip_block(src, "ai-billing-audit")

# Append the new router and service blocks. Traefik file-provider
# reloads on save, so no manual `curl POST /api/.../reload` is needed.
addition = """
  # ai-billing-audit (added by deploy-to-vps.sh $(date -u +%FT%TZ))
  ai-billing-audit:
    rule: "Host(`ai-billing-audit.ashbi.ca`)"
    entryPoints:
      - websecure
    service: ai-billing-audit
    tls:
      certResolver: letsencrypt

services:
  ai-billing-audit:
    loadBalancer:
      servers:
        - url: "http://127.0.0.1:3018"
"""
# If `services:` already exists, the new service block is appended
# under it. If not, we need to add the `services:` key. Same for the
# router — we append to the routers block, which is already in the
# existing file.
if "  routers:" not in src and "routers:" not in src:
    src += "http:\n  routers:\n" + addition
elif "services:" not in src and "service: ai-billing-audit" not in src:
    # Find where `http:` starts; if routers exist, insert `services:`
    # after the routers block (we use a placeholder for now).
    src = src.rstrip() + addition
else:
    src = src.rstrip() + addition

p.write_text(src)
print("wrote", p)
PYEOF

# Also write a TLS cert entry for the new hostname (matching the
# pattern in the existing tls.yml). We add an entry pointing at the
# per-host cert file; for new hostnames we rely on Let's Encrypt to
# issue on the first request, so this block is optional. We add a
# stub entry for symmetry with the other services so the file stays
# uniform; Traefik ignores it if the file doesn't exist.
if [ -f /etc/traefik/certs/ai-billing-audit.ashbi.ca.crt ]; then
    :
fi

echo "Traefik dynamic config updated"
REMOTE_TRAEFIK_EOF

# --- Step 4: docker compose build + up ---
log "docker compose build (api image)"
ssh "$HOST" "cd $REMOTE_DIR && docker compose build --pull" || fail "docker compose build failed"

log "docker compose up -d"
ssh "$HOST" "cd $REMOTE_DIR && docker compose up -d" || fail "docker compose up failed"

# Give the stack 15s to converge (postgres init + api boot).
log "wait 15s for stack to converge"
sleep 15

# --- Step 5: smoke tests ---
log "smoke 1/3: host-local curl http://127.0.0.1:$HOST_PORT/healthz"
ssh "$HOST" "curl -fsS --max-time 10 http://127.0.0.1:$HOST_PORT/healthz" \
    | tee /tmp/ai-billing-audit-healthz-local.json
echo

log "smoke 2/3: internal docker ps (all 4 services should be Up)"
ssh "$HOST" "cd $REMOTE_DIR && docker compose ps" || true

log "smoke 3/3: public https://$PUBLIC_HOSTNAME/healthz (waits up to 90s for cert issuance)"
SUCCESS=0
for i in 1 2 3 4 5 6 7 8 9; do
    if curl -fsS --max-time 10 "https://$PUBLIC_HOSTNAME/healthz" 2>/dev/null; then
        echo
        SUCCESS=1
        break
    fi
    printf "  attempt %d failed, retrying in 10s...\n" "$i"
    sleep 10
done
if [ "$SUCCESS" -ne 1 ]; then
    fail "public https://$PUBLIC_HOSTNAME/healthz never returned 200 within 90s"
fi

log "deploy complete"
log "  local URL : http://127.0.0.1:$HOST_PORT/healthz"
log "  public URL: https://$PUBLIC_HOSTNAME/healthz"
log "  host dir  : $HOST:$REMOTE_DIR"
