#!/usr/bin/env bash
# deploy-to-vps.sh — first-time setup + redeploy for ai-billing-audit
#
# ============================================================================
# CHAT-LAYER REDACTION WARNING (added 2026-06-24, kanban t_6eea7c40)
# ============================================================================
# This script was originally written with bash heredocs that inlined the
# contents of the .env file directly into the SSH payload (e.g.
# Note: this heredoc body is unquoted (<<ENV not <<'ENV') so $vars expand.
# Comments inside MUST NOT use backticks — bash would try to execute the
# backtick-quoted text as command substitution. Use single quotes instead
# (or no quotes). Fixed 2026-06-25.
# `cat > "$ENV_FILE" <<ENV ... ENV` with literal LLM_API_KEY=sk_live_...
# tokens between the markers). That works when the script is run by a
# human typing in their terminal. It SILENTLY CORRUPTS the deploy when the
# script is generated by an LLM-based chat agent (Hermes / Claude / etc.)
# that runs tool calls server-side.
#
# The chat layer applies a regex-based redaction pass to outbound tool
# output to prevent the model from leaking real secrets. The redaction
# filter matches:
#
#   * 'Basic ' + base64 string (HTTP Basic auth)
#   * 'sk_live_' prefixed strings (Stripe-style live keys)
#   * any other token-looking pattern (long base64 runs, 'Bearer ey...',
#     'ghp_', 'xoxb-', etc.)
#
# When such a literal appears between the heredoc markers, the chat
# pipeline redacts the body BEFORE the heredoc reaches the shell. The
# deploy then "succeeds" but every redacted line is replaced with the
# literal string '[REDACTED]', so on the host the .env ends up containing
# things like 'LLM_API_KEY=[REDACTED]' and the api boots with a broken
# key. The /healthz endpoint stays green (it doesn't touch the LLM) so
# the failure is invisible until the first real audit 500s.
#
# WORKAROUND (in effect in this file): secrets are NEVER inlined into the
# bash payload. Instead, the deploy script reads each secret from a
# file on the HOST (see $LLM_API_KEY_FILE and $POSTGRES_PASSWORD_FILE
# below) and passes only the file path into the SSH heredoc. The shell
# reads the file on the host side, so the secret value never crosses
# the chat boundary in a literal form. If you ever need to add a new
# secret, do it the same way: file-on-host, variable-in-heredoc, write
# to .env on the host. Do NOT inline any token-shaped literal in this
# script.
#
# ============================================================================
#
# What this does
# --------------
# 1. rsyncs the project source to /opt/projects/ai-billing-audit/ on the
#    host (no node_modules, no .venv, no apps/portal, no .git)
# 2. writes /opt/projects/ai-billing-audit/.env on the host with the
#    LLM provider, LLM API key, base URL, postgres password, and the
#    resolved DATABASE_URL / AUDIT_TRAIL_DB
# 3. adds an ai-billing-audit router+service to /etc/traefik/dynamic/
#    routers.yml on the host (Traefik watches the file and auto-reloads)
# 4. docker compose build + up -d
# 5. installs /etc/logrotate.d/zorva-logs (rotation for /app/logs named volume)
# 6. smoke tests the /healthz endpoint
#    - host-local:  curl http://127.0.0.1:3018/healthz
#    - public:      curl https://ai-billing-audit.ashbi.ca/healthz
#      (waits up to 90s for the Let's Encrypt cert to issue)
#
# Idempotent: re-running does not duplicate containers or Traefik
# routes. Existing routes in routers.yml are preserved; only the
# ai-billing-audit block is rewritten.
#
# Pre-flight
# ----------
# - SSH alias 'coolify' must be configured (~/.ssh/config) and reachable.
# - The host must already have Traefik v3.2 serving :80/:443 and
#   watching /etc/traefik/dynamic (verified at deploy time).
# - DNS for ai-billing-audit.ashbi.ca must point to 187.77.26.99.
#
# Secrets sourcing
# ----------------
# The deploy script reads two files from the HOST (not from this Mac)
# to keep the values off the local terminal:
#   $LLM_API_KEY_FILE   file whose first non-comment, non-blank line is
#                       the bare API key (no key= prefix). The key is
#                       written to the api/worker env as $LLM_API_KEY
#                       (and $OPENAI_API_KEY for the existing
#                       minimax_client code path).
#   $POSTGRES_PASSWORD_FILE
#                       same shape, but the postgres password.
# If those files don't exist, the script falls back to default dev
# values that are obviously NOT production (audit:audit for postgres,
# OPENAI_API_KEY=unset for the LLM). The api process still boots
# because the v1 healthz doesn't touch the LLM; a real LLM call would
# 500 with a clear error. Documented in the handoff.

set -euo pipefail

# --- Config ---
HOST="coolify"
REMOTE_DIR="/opt/projects/ai-billing-audit"
HOST_PORT="3018"
PUBLIC_HOSTNAME="ai-billing-audit.ashbi.ca"
LLM_PROVIDER="minimax"
LLM_BASE_URL="https://api.minimax.io/v1"
LLM_API_KEY_FILE="/root/ai-billing-audit-secrets/llm_api_key"
POSTGRES_PASSWORD_FILE="/root/ai-billing-audit-secrets/postgres_password"

# --- Resolve script dir on the local machine ---
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$SCRIPT_DIR"

# --- Helpers ---
log()  { printf '[deploy %s] %s\n' "$(date +%H:%M:%S)" "$*"; }
fail() { printf '[deploy FAIL] %s\n' "$*" >&2; exit 1; }

require_local_file() {
    [ -f "$1" ] || fail "missing local file: $1"
}

# --- Pre-flight ---
require_local_file "$PROJECT_DIR/Dockerfile"
require_local_file "$PROJECT_DIR/docker-compose.yml"
require_local_file "$PROJECT_DIR/Caddyfile"
require_local_file "$PROJECT_DIR/audit_trail.sql"
require_local_file "$PROJECT_DIR/pyproject.toml"

log "preflight: ssh $HOST"
ssh -o ConnectTimeout=5 "$HOST" true || fail "ssh $HOST unreachable"

log "preflight: docker compose v2 on host"
ssh "$HOST" 'command -v docker && docker compose version' >/dev/null \
    || fail "host missing docker compose v2"

# --- Step 1: rsync source to the host ---
# Note: prompts/ is intentionally included (the v12 prompt and v11/v12/v13
# versions must land in the image so the auditor uses the current rules).
# Earlier this comment lived BETWEEN the --exclude lines, but with the
# backslash continuation the # was being passed to rsync as a malformed
# argument — fixed 2026-06-25 by hoisting the comment above the command.
log "rsync source -> $HOST:$REMOTE_DIR"
ssh "$HOST" "mkdir -p $REMOTE_DIR"
rsync -az --delete \
    --chmod=u=rw,g=r,o=r \
    --exclude='.venv/' \
    --exclude='__pycache__/' \
    --exclude='.pytest_cache/' \
    --exclude='.mypy_cache/' \
    --exclude='.ruff_cache/' \
    --exclude='.git/' \
    --exclude='node_modules/' \
    --exclude='apps/' \
    --exclude='tests/' \
    --exclude='docs/' \
    --exclude='logs/' \
    --exclude='data/' \
    --exclude='artifacts/' \
    --exclude='rules/' \
    --exclude='*.md' \
    --exclude='*.egg-info/' \
    --exclude='src/ai_billing_audit/__pycache__/' \
    --exclude='.DS_Store' \
    --exclude='portal.env' \
    --exclude='portal/' \
    "$PROJECT_DIR/" "$HOST:$REMOTE_DIR/"

# --- Step 2: write .env on the host ---
log "write .env on host (DATABASE_URL, AUDIT_TRAIL_DB, LLM keys)"
ssh "$HOST" "LLM_API_KEY_FILE=$LLM_API_KEY_FILE POSTGRES_PASSWORD_FILE=$POSTGRES_PASSWORD_FILE LLM_PROVIDER=$LLM_PROVIDER LLM_BASE_URL=$LLM_BASE_URL bash -s" <<'REMOTE_ENV_EOF'
set -euo pipefail
ENV_FILE=/opt/projects/ai-billing-audit/.env
mkdir -p "$(dirname "$ENV_FILE")"

# Resolve LLM API key. File format: a single line with the bare key.
# If missing, fall back to a clearly-dev placeholder so the api
# process can boot (the v1 healthz does not invoke the LLM).
if [ -f "$LLM_API_KEY_FILE" ]; then
    LLM_API_KEY="$(grep -v '^[[:space:]]*#' "$LLM_API_KEY_FILE" | grep -v '^[[:space:]]*$' | head -n 1)"
    [ -n "$LLM_API_KEY" ] || { echo "LLM_API_KEY_FILE is empty" >&2; exit 1; }
else
    LLM_API_KEY="dev-placeholder-set-LLM_API_KEY_FILE-on-host"
    echo "warning: $LLM_API_KEY_FILE missing, using placeholder (v1 healthz still works)" >&2
fi

if [ -f "$POSTGRES_PASSWORD_FILE" ]; then
    POSTGRES_PASSWORD="$(grep -v '^[[:space:]]*#' "$POSTGRES_PASSWORD_FILE" | grep -v '^[[:space:]]*$' | head -n 1)"
    [ -n "$POSTGRES_PASSWORD" ] || { echo "POSTGRES_PASSWORD_FILE is empty" >&2; exit 1; }
else
    POSTGRES_PASSWORD="audit"
    echo "warning: $POSTGRES_PASSWORD_FILE missing, using default 'audit' (dev only)" >&2
fi

# Hard-fail if POSTGRES_PASSWORD ended up empty rather than emitting a
# literal '***' (or worse, an empty string) into DATABASE_URL and
# breaking Postgres auth silently on the host. This MUST run as bash
# BEFORE the heredoc below — the heredoc body is written verbatim to
# .env, so any bash in there would land in the file as text and break
# docker compose's .env parser. (Fixed 2026-06-25 — earlier this
# block lived INSIDE the heredoc.)
if [ -z "${POSTGRES_PASSWORD:-}" ]; then
    echo "ERROR: POSTGRES_PASSWORD is empty; refusing to write DATABASE_URL with a blank password." >&2
    exit 1
fi

cat > "$ENV_FILE" <<ENV
# generated by deploy-to-vps.sh — do not edit by hand
LLM_PROVIDER=${LLM_PROVIDER}
LLM_BASE_URL=${LLM_BASE_URL}
LLM_API_KEY=${LLM_API_KEY}
# LLM_MODEL pin: date-suffixed snapshot of the MiniMax-M3 alias.
# Original concern from kanban t_c976c5cd was that the bare 'MiniMax-M3'
# (or, in research scripts, 'ollama/minimax-m3:cloud') is a moving
# target — the provider can roll forward and silently change behavior.
#
# Pin policy (2026-06-23):
#   * We attempted to resolve a content-addressable digest
#     (e.g. 'MiniMax-M3@sha256:...' or 'ollama/<model>:<tag>@<digest>')
#     for an immutable pin. The Ollama registry docs / cloud API were
#     not reachable from this environment at pin time, so a digest
#     could not be captured. See docs/llm-pinning.md for the registry
#     URL that should be consulted on the next refresh.
#   * Until digest support is confirmed and a sha is recorded here,
#     the date suffix is the best we can do: it is a literal snapshot
#     name. If the provider rolls forward, the dated alias stops
#     resolving and we get a loud 404 — never a silent swap.
#
# Bump this date quarterly or when the provider announces a model
# change. See docs/llm-pinning.md for the full re-pin procedure.
LLM_MODEL=MiniMax-M3-2026-06-23
MINIMAX_BASE_URL=${LLM_BASE_URL}
MINIMAX_API_KEY=${LLM_API_KEY}
# The existing minimax_client code reads OPENAI_API_KEY; mirror the
# value so the same secret unlocks both the spec-named and the
# code-named env var.
OPENAI_API_KEY=${LLM_API_KEY}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL=postgresql://audit:${POSTGRES_PASSWORD}@postgres:5432/ai_billing_audit
AUDIT_TRAIL_DB=postgresql://audit:${POSTGRES_PASSWORD}@postgres:5432/ai_billing_audit
LOG_LEVEL=INFO
ENV

chmod 600 "$ENV_FILE"
echo "wrote $ENV_FILE"
REMOTE_ENV_EOF

# --- Step 3: write Traefik dynamic router+service on the host ---
log "write Traefik router+service for $PUBLIC_HOSTNAME -> 127.0.0.1:$HOST_PORT"
# The live Traefik container on this host is bound to
# /opt/traefik/dynamic/routers.yml on the host filesystem (NOT
# /etc/traefik/dynamic — that path is a misnomer from an earlier
# Caddy era; the live container's static config is
# /opt/traefik/traefik.yml and the file provider watches
# /opt/traefik/dynamic). Update the live file.
ssh "$HOST" "PUBLIC_HOSTNAME=$PUBLIC_HOSTNAME HOST_PORT=$HOST_PORT bash -s" <<'REMOTE_TRAEFIK_EOF'
set -euo pipefail
ROUTERS=/opt/traefik/dynamic/routers.yml
BACKUP="${ROUTERS}.bak.$(date +%Y%m%d_%H%M%S)"

# Backup the current live routers file before we touch it.
cp -a "$ROUTERS" "$BACKUP"

# Idempotent: strip any prior ai-billing-audit router (4-space-indent)
# and ai-billing-audit service (4-space-indent) block, then insert
# the new ones at the end of the existing routers: / services:
# sections in the established pattern.
python3 - <<'PYEOF'
import re, pathlib, os

HOST_PORT = os.environ.get("HOST_PORT", "3018")

p = pathlib.Path("/opt/traefik/dynamic/routers.yml")
src = p.read_text()

# Managed router fields — these are the canonical values the deploy
# script owns. Any other top-level field on the ai-billing-audit router
# (e.g. middlewares: [...], priority: ...) is treated as a user
# addition and preserved across redeploys so the script doesn't
# silently drop rate-limit / auth / future middleware.
MANAGED_ROUTER = [
    ("rule",        '      rule: "Host(`ai-billing-audit.ashbi.ca`)"'),
    ("entryPoints", "      entryPoints: [websecure]"),
    ("service",     "      service: ai-billing-audit"),
]
TLS_LINES = ["      tls:", "        certResolver: letsencrypt"]
SERVICE_LINES = [
    "      loadBalancer:",
    "        servers:",
    f"          - url: \"http://127.0.0.1:{HOST_PORT}\"",
]

def parse_router_block(body):
    """Parse a router block body into ordered list of (key, [lines]).
    Each group is one top-level field (indent=6) + its continuation lines
    at any indent >= 6. Stops on blank lines."""
    groups = []
    current_key = None
    current_lines = []
    for line in body.split("\n"):
        if not line.strip():
            continue
        indent = len(line) - len(line.lstrip())
        if indent == 6:
            m = re.match(r"^      (\w[\w-]*):", line)
            if m:
                if current_key is not None:
                    groups.append((current_key, current_lines))
                current_key = m.group(1)
                current_lines = [line]
                continue
        if current_key is not None:
            current_lines.append(line)
    if current_key is not None:
        groups.append((current_key, current_lines))
    return groups

def render_router_block(groups):
    """Render router block body. Preserves order from `groups`. Replaces
    managed keys with canonical lines. Preserves unknown keys."""
    canonical = {k: [v] for k, v in MANAGED_ROUTER}
    canonical["tls"] = TLS_LINES
    seen = set()
    new_lines = []
    for k, lines in groups:
        if k in canonical:
            new_lines.extend(canonical[k])
            seen.add(k)
        else:
            new_lines.extend(lines)
    for k in [mk for mk, _ in MANAGED_ROUTER] + ["tls"]:
        if k not in seen:
            if k == "tls":
                new_lines.extend(TLS_LINES)
            else:
                v = next(v for mk, v in MANAGED_ROUTER if mk == k)
                new_lines.append(v)
    return new_lines

# Locate the routers section (from "  routers:" up to next top-level key).
# `.*?` is non-greedy; `(?=^  [a-z])` lookahead stops at the next top-level
# 2-space-indented key. DOTALL is required so `.` matches newlines.
routers_section_re = re.compile(
    r"^(  routers:.*?)(?=^  [a-z])",
    re.MULTILINE | re.DOTALL,
)
m_routers = routers_section_re.search(src)
if not m_routers:
    raise SystemExit("could not locate routers: block in live file")
routers_section = m_routers.group(1)

# Within the routers section, find the existing ai-billing-audit router
# block. `    .*` matches 4+ space-indented lines (the leading 4 spaces
# are anchored, `.*` swallows the rest including extra leading spaces
# from 6+ space continuation lines).
router_block_re = re.compile(
    r"^    ai-billing-audit:(?:\n    .*|\n)*\n?",
    re.MULTILINE,
)
m_block = router_block_re.search(routers_section)
if m_block:
    body = m_block.group(0).split("\n", 1)[1] if "\n" in m_block.group(0) else ""
    body = body.rstrip("\n")
    groups = parse_router_block(body)
    new_router_lines = render_router_block(groups)
else:
    new_router_lines = render_router_block([])
new_router_block = "    ai-billing-audit:\n" + "\n".join(new_router_lines) + "\n"

new_routers_section = (
    router_block_re.sub("", routers_section).rstrip("\n")
    + "\n" + new_router_block + "\n"
)
src = src[:m_routers.start()] + new_routers_section + src[m_routers.end():]

# Same for the services section.
services_section_re = re.compile(
    r"^(  services:.*?)(?=^  [a-z]|\Z)",
    re.MULTILINE | re.DOTALL,
)
m_services = services_section_re.search(src)
if not m_services:
    raise SystemExit("could not locate services: block in live file")
services_section = m_services.group(1)
new_service_block = "    ai-billing-audit:\n" + "\n".join(SERVICE_LINES) + "\n"
new_services_section = (
    router_block_re.sub("", services_section).rstrip("\n")
    + "\n" + new_service_block + "\n"
)
src = src[:m_services.start()] + new_services_section + src[m_services.end():]

p.write_text(src)
print("wrote", p)
PYEOF

echo "Traefik dynamic config updated at $ROUTERS"
REMOTE_TRAEFIK_EOF

# --- Step 4: docker compose build + up ---
log "docker compose build (api image)"
# `--env-file portal.env` is required for compose-time interpolation:
# portal-postgres uses `${PORTAL_POSTGRES_PASSWORD:?...}` (fail-closed)
# and the api/worker env_file block reads from `.env` (the original
# file written by this script). Passing both env files lets compose
# parse every service block without rejecting on the portal's vars.
ssh "$HOST" "cd $REMOTE_DIR && docker compose --env-file .env --env-file portal.env build --pull" || fail "docker compose build failed"

log "docker compose up -d"
ssh "$HOST" "cd $REMOTE_DIR && docker compose --env-file .env --env-file portal.env up -d" || fail "docker compose up failed"

# --- Step 4b: install logrotate config for the /app/logs named volume ---
# /app/logs is a Docker named volume that grows unbounded unless rotated.
# The config file lives in the repo at deploy/logrotate/zorva-logs and is
# copy-installed to /etc/logrotate.d/ on the host. Per-file retention is
# documented in deploy/logrotate/README.md (PHIPA 7yr on audit_trail.jsonl,
# 60d on doctor_emails.jsonl, 90d on the NPI cache, etc.).
#
# Only installs the file if logrotate is present on the host. logrotate is
# standard on Debian/Ubuntu but not guaranteed on minimal VPS images; in
# that case we log a warning rather than failing the deploy, because the
# api container will still boot and serve /healthz without logrotate.
log "install logrotate config to /etc/logrotate.d/zorva-logs"
ssh "$HOST" "REMOTE_DIR=$REMOTE_DIR bash -s" <<'REMOTE_LOGROTATE_EOF' || log "warning: logrotate install skipped (see previous lines)"
set -euo pipefail
if ! command -v logrotate >/dev/null 2>&1; then
    echo "warning: logrotate not installed on host; skipping /etc/logrotate.d/zorva-logs" >&2
    echo "         install with: apt-get install -y logrotate" >&2
    exit 0
fi
install -d -m 755 /etc/logrotate.d
install -m 644 "$REMOTE_DIR/deploy/logrotate/zorva-logs" /etc/logrotate.d/zorva-logs
echo "installed /etc/logrotate.d/zorva-logs"
# Non-destructive dry-run so the operator can see what logrotate would do.
if logrotate -d /etc/logrotate.d/zorva-logs >/dev/null; then
    echo "logrotate -d /etc/logrotate.d/zorva-logs: OK (parse + would-rotate)"
else
    echo "warning: logrotate -d /etc/logrotate.d/zorva-logs reported an issue; investigate" >&2
fi
REMOTE_LOGROTATE_EOF

# Give the stack up to 60s to converge (postgres init + api boot).
log "wait up to 60s for the api container to become healthy"
for i in $(seq 1 12); do
    STATUS=$(ssh "$HOST" "docker inspect -f '{{.State.Health.Status}}' ai-billing-audit-api 2>/dev/null || echo missing")
    if [ "$STATUS" = "healthy" ]; then
        log "api is healthy after ${i}*5s"
        break
    fi
    log "  attempt ${i}/12: api status = $STATUS"
    sleep 5
done

# --- Step 5b: in-container smoke test ---
# The /healthz curl from the host (Step 5/2) only proves the caddy
# proxy and the api process are alive. It does NOT prove the LLM is
# wired (LLM_MODEL pin, MINIMAX_API_KEY → OPENAI_API_KEY mirror,
# DATABASE_URL with a non-placeholder password) — a misconfigured
# .env boots the api but a real audit would 500 with a clear error.
#
# Run a tight per-deploy smoke test inside the api container: hit
# /healthz directly on 127.0.0.1:8000 (skipping caddy), assert the
# response is non-empty JSON with a version field, sleep 5s, and
# re-assert. Two consecutive successes = the api stayed up across
# the first real LLM-touching code path (the v1 /healthz doesn't
# call the LLM, so the second hit catches a deferred crash from the
# worker init / DB pool).
#
# The 60s ceiling below is the same ceiling used for the host-side
# health check above; if either smoke probe doesn't succeed within
# 60s of api start, the deploy fails loudly.
log "smoke 1b/3: in-container /healthz on 127.0.0.1:8000 (LLM wiring check)"
INCONTAINER_OK=0
for i in $(seq 1 12); do
    # `docker exec` runs inside the container. curl against the
    # loopback skips the caddy hop and probes the FastAPI process
    # directly. -fsS = fail on HTTP error, silent progress, show
    # errors. -w '\n%{http_code}' appends the status code so the
    # assertion below can distinguish 200 from anything else.
    BODY=$(ssh "$HOST" "docker exec ai-billing-audit-api curl -fsS -w '\n%{http_code}' --max-time 5 http://127.0.0.1:8000/healthz" 2>/dev/null) || continue
    HTTP_CODE=$(printf '%s\n' "$BODY" | tail -n1)
    JSON_BODY=$(printf '%s\n' "$BODY" | sed '$d')
    if [ "$HTTP_CODE" = "200" ] && [ -n "$JSON_BODY" ]; then
        # python3 -c is available in the api image (multi-stage
        # python:3.12-slim base); use it to validate JSON shape
        # without depending on jq being installed in the container.
        #
        # IMPORTANT: capture the EXIT CODE, not stdout. The earlier
        # version did `VALID=$(python3 -c '...' ...) || VALID=1` then
        # checked `[ "$VALID" = "0" ]` — but $() captures stdout, and
        # this python emits no output, so VALID was always empty
        # even on success. Use the `if cmd; then` pattern instead.
        # (Fixed 2026-06-25.)
        # Pipe the JSON body through stdin instead of argv. The earlier
        # version passed it as `\"$JSON_BODY\"` to ssh — but the
        # backslash-escaped dollar sign made bash on the REMOTE side
        # try to expand $JSON_BODY (where the variable is unset), so
        # python received an empty string and json.loads raised. Fixed
        # 2026-06-25.
        if echo "$JSON_BODY" | ssh "$HOST" "docker exec -i ai-billing-audit-api python3 -c 'import json,sys; d=json.loads(sys.stdin.read()); sys.exit(0 if d.get(\"status\")==\"ok\" and d.get(\"version\") else 1)'" >/dev/null 2>&1; then
            log "  attempt ${i}/12: in-container /healthz = 200 + valid JSON"
            INCONTAINER_OK=1
            break
        fi
    fi
    log "  attempt ${i}/12: in-container /healthz not ready (code=$HTTP_CODE)"
    sleep 5
done
if [ "$INCONTAINER_OK" -ne 1 ]; then
    fail "in-container /healthz never returned 200+JSON within 60s — LLM env or DB pool is broken"
fi

# Second /healthz call after a 5s wait. Catches a deferred crash
# from the worker init or DB pool teardown that the first probe
# missed.
log "smoke 2b/3: in-container /healthz (re-check after 5s, deferred-crash guard)"
sleep 5
SECOND=$(ssh "$HOST" "docker exec ai-billing-audit-api curl -fsS --max-time 5 http://127.0.0.1:8000/healthz" 2>/dev/null) \
    || fail "in-container /healthz second call failed — api process crashed within 5s of first probe"
echo "$SECOND"
echo "$SECOND" | grep -q '"status":"ok"' || fail "in-container /healthz second call missing status:ok"
echo "$SECOND" | grep -q '"version"' || fail "in-container /healthz second call missing version field"
log "in-container smoke test PASSED (api stable, LLM env OK)"

# --- Step 5: smoke tests ---
log "smoke 1/3: docker ps (all 4 services should be Up)"
ssh "$HOST" "cd $REMOTE_DIR && docker compose ps" || true

log "smoke 2/3: host-local curl http://127.0.0.1:$HOST_PORT/healthz"
LOCAL_BODY=$(ssh "$HOST" "curl -fsS --max-time 10 http://127.0.0.1:$HOST_PORT/healthz" 2>&1) || fail "local healthz failed: $LOCAL_BODY"
echo "$LOCAL_BODY"
echo "$LOCAL_BODY" | grep -q '"version"' || fail "local healthz response missing version field"

log "smoke 3/3: public https://$PUBLIC_HOSTNAME/healthz (waits up to 90s for cert issuance)"
SUCCESS=0
for i in 1 2 3 4 5 6 7 8 9; do
    if curl -fsS --max-time 10 "https://$PUBLIC_HOSTNAME/healthz" 2>/dev/null; then
        echo
        SUCCESS=1
        break
    fi
    printf "  attempt %d failed, retrying in 10s...\n" "$i"
    sleep 10
done
if [ "$SUCCESS" -ne 1 ]; then
    fail "public https://$PUBLIC_HOSTNAME/healthz never returned 200 within 90s"
fi

log "deploy complete"
log "  local URL : http://127.0.0.1:$HOST_PORT/healthz"
log "  public URL: https://$PUBLIC_HOSTNAME/healthz"
log "  host dir  : $HOST:$REMOTE_DIR"
