"""Auto-generated tests for ``ai_billing_audit.clinical_metrics``.

Generated by test-generator subagent. Focus: branches-and-edges of the
public helper surface (every name in ``clinical_metrics.__all__``).
The FastAPI HTTP layer is intentionally NOT re-tested here — the
existing ``test_clinical_metrics.py`` and ``test_clinical_metrics_surfaces.py``
files already cover the mounted routes end-to-end.

What's pinned
-------------
* Every public dataclass round-trips through ``to_dict``.
* Every helper's happy path persists → reload returns the same row.
* Validation raises ``ValueError`` with a useful message on bad input.
* Cross-clinic / cross-doctor filtering isolates one tenant from another.
* Empty-log / empty-input edge cases return a structured response
  rather than crashing.
* ``compute_doctor_effectiveness`` and ``run_feedback_loop_week`` both
  fall back to empty results when the underlying ``FeedbackStore``
  raises (defensive exception guard).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Iterator

import pytest


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def tmp_logs(monkeypatch, tmp_path: Path) -> Iterator[None]:
    """Redirect every JSONL log path the module reads/writes into tmp.

    Mirrors the pattern in ``test_clinical_metrics_surfaces.py`` so the
    file-level state stays isolated per test. Each helper resolves its
    path via a ``*_path_path()`` function that reads the env var on
    every call (no module-level cache), so monkeypatch is sufficient.
    """
    paths = {
        "CLINIC_PROMPT_PIN_LOG": "clinic_prompt_pins.jsonl",
        "TEACHING_VERDICT_LOG": "teaching_verdicts.jsonl",
        "REAUDIT_QUEUE_LOG": "reaudit_queue.jsonl",
        "DOCTOR_DASHBOARD_LOG": "doctor_dashboard.jsonl",
        "NOTE_SUGGESTION_LOG": "note_suggestions.jsonl",
        "OWNER_EMAIL_LOG": "owner_emails.jsonl",
        "SUBMIT_WEBHOOK_LOG": "submit_webhooks.jsonl",
        "FEEDBACK_LOOP_LOG": "feedback_loop_runs.jsonl",
        "TENANT_RULES_LOG": "tenant_rules.jsonl",
        "ONBOARDING_LOG": "onboarding.jsonl",
        "PRE_SUBMIT_BLOCKING_LOG": "pre_submit_blocking.jsonl",
        "BROWSER_EXTENSION_LOG": "browser_extension.jsonl",
        "SPECIALTY_MIX_LOG": "specialty_mix.jsonl",
        "BULK_ACCEPT_LOG": "bulk_accept_patterns.jsonl",
        "POSITIVE_FEEDBACK_LOG": "doctor_positive_feedback.jsonl",
        "FEEDBACK_LOG": "feedback.jsonl",
    }
    for env, name in paths.items():
        monkeypatch.setenv(env, str(tmp_path / name))
    yield


# ---------------------------------------------------------------------------
# Dataclasses
# ---------------------------------------------------------------------------


def test_prompt_pin_dataclass_defaults(tmp_logs) -> None:
    """Default-constructed pin has ISO timestamp + uuid event_id."""
    from ai_billing_audit.clinical_metrics import PromptPin

    pin = PromptPin(clinic_id="clinic_a", prompt_version_id="v12")
    d = pin.to_dict()
    assert d["clinic_id"] == "clinic_a"
    assert d["prompt_version_id"] == "v12"
    assert d["actor"] == "admin"
    assert len(d["event_id"]) == 32  # uuid4 hex
    assert d["timestamp"].endswith("Z")


def test_teaching_verdict_dataclass_defaults(tmp_logs) -> None:
    from ai_billing_audit.clinical_metrics import TeachingVerdict

    v = TeachingVerdict(
        feedback_id="fb_1", clinic_id="clinic_a",
        finding_id="f1", verdict="doctor_right",
    )
    d = v.to_dict()
    assert d["verdict"] == "doctor_right"
    assert d["notes"] == ""
    assert d["actor"] == "admin"
    assert len(d["event_id"]) == 32


# ---------------------------------------------------------------------------
# compute_doctor_effectiveness (t_267a1ad6)
# ---------------------------------------------------------------------------


def test_compute_doctor_effectiveness_empty_log(tmp_logs) -> None:
    """Empty log → status=insufficient_data, all numeric fields None."""
    from ai_billing_audit.clinical_metrics import compute_doctor_effectiveness

    payload = compute_doctor_effectiveness("doc_1", "clinic_a")
    assert payload["status"] == "insufficient_data"
    assert payload["doctor_id"] == "doc_1"
    assert payload["clinic_id"] == "clinic_a"
    assert payload["current_quarter_flags_per_encounter"] is None


def test_compute_doctor_effectiveness_groups_by_encounter(tmp_logs) -> None:
    """Counts flags per encounter, computes flags/encounter ratio."""
    from ai_billing_audit.clinical_metrics import compute_doctor_effectiveness

    log = [
        {"encounter_id": "e1", "doctor_id": "doc_1", "action": "accept"},
        {"encounter_id": "e1", "doctor_id": "doc_1", "action": "dismiss"},
        {"encounter_id": "e2", "doctor_id": "doc_1", "action": "accept"},
        # Different doctor — must be filtered out
        {"encounter_id": "e3", "doctor_id": "other", "action": "accept"},
    ]
    payload = compute_doctor_effectiveness(
        "doc_1", "clinic_a", feedback_log=log,
    )
    assert payload["status"] == "ok"
    assert payload["encounters_with_feedback"] == 2
    # 3 flags across 2 encounters = 1.5
    assert payload["current_quarter_flags_per_encounter"] == 1.5


def test_compute_doctor_effectiveness_no_matches_for_doctor(tmp_logs) -> None:
    """Rows exist but none belong to this doctor → insufficient_data."""
    from ai_billing_audit.clinical_metrics import compute_doctor_effectiveness

    log = [
        {"encounter_id": "e1", "doctor_id": "someone_else", "action": "accept"},
    ]
    payload = compute_doctor_effectiveness(
        "doc_1", "clinic_a", feedback_log=log,
    )
    assert payload["status"] == "insufficient_data"
    assert "No feedback entries" in payload["message"]


def test_compute_doctor_effectiveness_skips_rows_without_encounter_id(tmp_logs) -> None:
    """Defensive: rows missing encounter_id are dropped, not crashed on."""
    from ai_billing_audit.clinical_metrics import compute_doctor_effectiveness

    log = [
        {"doctor_id": "doc_1", "action": "accept"},  # no encounter_id
        {"encounter_id": "e1", "doctor_id": "doc_1", "action": "accept"},
    ]
    payload = compute_doctor_effectiveness(
        "doc_1", "clinic_a", feedback_log=log,
    )
    assert payload["status"] == "ok"
    assert payload["encounters_with_feedback"] == 1


def test_compute_doctor_effectiveness_swallows_feedback_store_error(tmp_logs, monkeypatch) -> None:
    """If ``FeedbackStore.read_all`` raises, the helper returns insufficient_data
    rather than bubbling the exception. This is the lazy-import fallback path.
    """
    from ai_billing_audit import clinical_metrics, feedback as _feedback

    class _BoomStore:
        def read_all(self):
            raise RuntimeError("disk full")

    monkeypatch.setattr(_feedback, "FeedbackStore", _BoomStore)
    # Pass feedback_log=None so the helper takes the FeedbackStore branch
    payload = clinical_metrics.compute_doctor_effectiveness("doc_1", "clinic_a")
    assert payload["status"] == "insufficient_data"


# ---------------------------------------------------------------------------
# Teaching-signal queue + verdict (t_a26d25be)
# ---------------------------------------------------------------------------


def _seed_incorrect_feedback_row(path: Path, **fields) -> None:
    """Append a raw JSON line to FEEDBACK_LOG (the helper reads the file
    directly because FeedbackStore rejects 'incorrect' as an action).
    """
    row = {
        "encounter_id": "e1",
        "finding_id": "f1",
        "action": "incorrect",
        "doctor_id": "doctor_1",
        "clinic_id": "clinic_a",
        "rule_id": "r1",
        "severity": "low",
        "category": "documentation",
        "biller_id": "doctor_1",
        "timestamp": "2026-06-25T00:00:00Z",
        "event_id": "fb_seed_1",
    }
    row.update(fields)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(row) + "\n")


def test_list_teaching_signal_queue_filters_by_clinic(tmp_logs) -> None:
    """Only rows whose clinic_id matches come back."""
    from ai_billing_audit.clinical_metrics import list_teaching_signal_queue

    log_path = Path(__import__("os").environ["FEEDBACK_LOG"])
    _seed_incorrect_feedback_row(log_path, clinic_id="clinic_a")
    _seed_incorrect_feedback_row(
        log_path,
        clinic_id="clinic_b",
        event_id="fb_seed_2",
        finding_id="f2",
    )
    rows = list_teaching_signal_queue(clinic_id="clinic_a")
    assert len(rows) == 1
    assert rows[0]["clinic_id"] == "clinic_a"


def test_list_teaching_signal_queue_returns_all_without_filter(tmp_logs) -> None:
    from ai_billing_audit.clinical_metrics import list_teaching_signal_queue

    log_path = Path(__import__("os").environ["FEEDBACK_LOG"])
    _seed_incorrect_feedback_row(log_path, clinic_id="clinic_a")
    _seed_incorrect_feedback_row(
        log_path,
        clinic_id="clinic_b",
        event_id="fb_seed_2",
        finding_id="f2",
    )
    rows = list_teaching_signal_queue()
    assert len(rows) == 2


def test_list_teaching_signal_queue_ignores_non_incorrect_rows(tmp_logs) -> None:
    """Accept/dismiss/modify rows must not appear in the teaching queue."""
    from ai_billing_audit.clinical_metrics import list_teaching_signal_queue

    log_path = Path(__import__("os").environ["FEEDBACK_LOG"])
    log_path.parent.mkdir(parents=True, exist_ok=True)
    with log_path.open("a", encoding="utf-8") as fh:
        # Non-incorrect action
        fh.write(
            json.dumps(
                {
                    "encounter_id": "e1", "finding_id": "f1",
                    "action": "accept", "clinic_id": "clinic_a",
                    "event_id": "fb_accept_1",
                }
            ) + "\n"
        )
        _seed_incorrect_feedback_row(log_path)

    assert len(list_teaching_signal_queue()) == 1


def test_record_teaching_verdict_round_trip(tmp_logs) -> None:
    from ai_billing_audit.clinical_metrics import (
        TeachingVerdict,
        list_do_not_flag_rules,
        record_teaching_verdict,
    )

    verdict = TeachingVerdict(
        feedback_id="fb_1",
        clinic_id="clinic_a",
        finding_id="f1",
        verdict="doctor_right",
        notes="Modifier-25 was correct per specialty guidance",
    )
    returned = record_teaching_verdict(verdict)
    assert returned.event_id == verdict.event_id

    rules = list_do_not_flag_rules("clinic_a")
    assert len(rules) == 1
    assert rules[0]["verdict"] == "doctor_right"
    assert "Modifier-25" in rules[0]["notes"]


def test_list_do_not_flag_rules_isolates_clinics(tmp_logs) -> None:
    """Only doctor_right verdicts for THIS clinic come back."""
    from ai_billing_audit.clinical_metrics import (
        TeachingVerdict,
        list_do_not_flag_rules,
        record_teaching_verdict,
    )

    record_teaching_verdict(
        TeachingVerdict(
            feedback_id="fb_a", clinic_id="clinic_a",
            finding_id="f1", verdict="doctor_right",
        )
    )
    record_teaching_verdict(
        TeachingVerdict(
            feedback_id="fb_b", clinic_id="clinic_b",
            finding_id="f2", verdict="doctor_right",
        )
    )
    record_teaching_verdict(
        TeachingVerdict(
            feedback_id="fb_c", clinic_id="clinic_a",
            finding_id="f3", verdict="auditor_right",  # different verdict
        )
    )

    clinic_a_rules = list_do_not_flag_rules("clinic_a")
    assert len(clinic_a_rules) == 1
    assert clinic_a_rules[0]["feedback_id"] == "fb_a"


def test_list_do_not_flag_rules_empty_log(tmp_logs) -> None:
    from ai_billing_audit.clinical_metrics import list_do_not_flag_rules

    assert list_do_not_flag_rules("clinic_a") == []


# ---------------------------------------------------------------------------
# Re-audit queue (t_f5ea3bf2)
# ---------------------------------------------------------------------------


def test_queue_reaudit_round_trip(tmp_logs) -> None:
    from ai_billing_audit.clinical_metrics import list_reaudit_queue, queue_reaudit

    payload = queue_reaudit("enc_a", actor="doctor_1", note="updated")
    assert payload["status"] == "queued"
    assert payload["actor"] == "doctor_1"
    assert len(payload["event_id"]) == 32

    queue = list_reaudit_queue()
    assert len(queue) == 1
    assert queue[0]["encounter_id"] == "enc_a"


def test_list_reaudit_queue_empty(tmp_logs) -> None:
    from ai_billing_audit.clinical_metrics import list_reaudit_queue

    assert list_reaudit_queue() == []


# ---------------------------------------------------------------------------
# Per-clinic prompt version pin (t_17ec5fec)
# ---------------------------------------------------------------------------


def test_pin_prompt_version_overwrites(tmp_logs) -> None:
    """Re-pinning a clinic replaces the prior version (last-write-wins)."""
    from ai_billing_audit.clinical_metrics import (
        get_pinned_prompt_version,
        list_pinned_clinics,
        pin_prompt_version,
    )

    assert get_pinned_prompt_version("clinic_a") is None

    pin_prompt_version("clinic_a", "v12", actor="admin")
    assert get_pinned_prompt_version("clinic_a") == "v12"

    pin_prompt_version("clinic_a", "v13", actor="admin")
    assert get_pinned_prompt_version("clinic_a") == "v13"

    pinned = list_pinned_clinics()
    assert pinned == {"clinic_a": "v13"}


def test_get_pinned_prompt_version_isolates_clinics(tmp_logs) -> None:
    from ai_billing_audit.clinical_metrics import (
        get_pinned_prompt_version,
        pin_prompt_version,
    )

    pin_prompt_version("clinic_a", "v12")
    pin_prompt_version("clinic_b", "v9")
    assert get_pinned_prompt_version("clinic_a") == "v12"
    assert get_pinned_prompt_version("clinic_b") == "v9"
    assert get_pinned_prompt_version("clinic_c") is None


def test_list_pinned_clinics_drops_blank_ids(tmp_logs) -> None:
    """Rows missing clinic_id or prompt_version_id are skipped, not crashed on."""
    import os

    from ai_billing_audit.clinical_metrics import list_pinned_clinics

    log_path = Path(os.environ["CLINIC_PROMPT_PIN_LOG"])
    log_path.parent.mkdir(parents=True, exist_ok=True)
    with log_path.open("w", encoding="utf-8") as fh:
        fh.write(json.dumps({"clinic_id": "", "prompt_version_id": "v0"}) + "\n")
        fh.write(json.dumps({"clinic_id": "clinic_a", "prompt_version_id": ""}) + "\n")
        fh.write(json.dumps({"clinic_id": "clinic_b", "prompt_version_id": "v9"}) + "\n")

    pinned = list_pinned_clinics()
    assert pinned == {"clinic_b": "v9"}


# ---------------------------------------------------------------------------
# Doctor dashboard view (t_af26abdb)
# ---------------------------------------------------------------------------


def test_log_doctor_dashboard_view_round_trip(tmp_logs) -> None:
    from ai_billing_audit.clinical_metrics import (
        list_doctor_dashboard_views,
        log_doctor_dashboard_view,
    )

    payload = log_doctor_dashboard_view(
        "doc_1", "clinic_a",
        flagged_encounters=3, awaiting_review=1,
        clean_rate=0.94, savings_usd=340.0,
    )
    assert payload["doctor_id"] == "doc_1"
    assert payload["flagged_encounters"] == 3
    assert payload["clean_rate"] == 0.94

    rows = list_doctor_dashboard_views("clinic_a")
    assert len(rows) == 1
    # Other clinic: isolation
    assert list_doctor_dashboard_views("other") == []


# ---------------------------------------------------------------------------
# Note suggestion (t_df188436)
# ---------------------------------------------------------------------------


def test_record_note_suggestion_round_trip(tmp_logs) -> None:
    from ai_billing_audit.clinical_metrics import (
        list_note_suggestions,
        record_note_suggestion,
    )

    record_note_suggestion(
        finding_id="f1", encounter_id="enc_1", clinic_id="clinic_a",
        suggested_addition="Patient has failed 6 weeks of NSAIDs + PT.",
    )
    rows = list_note_suggestions("enc_1")
    assert len(rows) == 1
    assert rows[0]["finding_id"] == "f1"
    assert list_note_suggestions("enc_other") == []


@pytest.mark.parametrize("bad_text", ["", "   ", "\n\t  "])
def test_record_note_suggestion_blank_raises(tmp_logs, bad_text) -> None:
    from ai_billing_audit.clinical_metrics import record_note_suggestion

    with pytest.raises(ValueError, match="non-empty"):
        record_note_suggestion(
            finding_id="f1", encounter_id="enc_1",
            clinic_id="clinic_a", suggested_addition=bad_text,
        )


# ---------------------------------------------------------------------------
# Owner monthly email (t_a8eeb0de)
# ---------------------------------------------------------------------------


def test_queue_owner_monthly_email_round_trip(tmp_logs) -> None:
    from ai_billing_audit.clinical_metrics import (
        list_owner_emails,
        queue_owner_monthly_email,
    )

    payload = queue_owner_monthly_email(
        "clinic_a",
        claims_submitted=412, clean_rate=0.94,
        estimated_savings_usd=14200.0, review_resolution_days=2.0,
        peer_percentile=75,
    )
    assert payload["status"] == "queued"
    assert payload["peer_percentile"] == 75
    assert payload["claims_submitted"] == 412
    assert list_owner_emails("clinic_a") == [payload]
    assert list_owner_emails("other") == []


# ---------------------------------------------------------------------------
# Submit webhook (t_3b15809f)
# ---------------------------------------------------------------------------


def test_record_submit_webhook_round_trip(tmp_logs) -> None:
    from ai_billing_audit.clinical_metrics import (
        list_submit_webhooks,
        record_submit_webhook,
    )

    record_submit_webhook(
        clinic_id="clinic_a", encounter_id="enc_1",
        verdict="flagged", findings=[{"id": "f1"}, {"id": "f2"}],
        hmac_ok=True, latency_ms=2400,
    )
    rows = list_submit_webhooks("clinic_a")
    assert len(rows) == 1
    assert rows[0]["findings_count"] == 2
    assert rows[0]["hmac_ok"] is True
    assert list_submit_webhooks("other") == []


@pytest.mark.parametrize("bad_verdict", ["bogus", "approve", "", "CLEAN"])
def test_record_submit_webhook_bad_verdict_raises(tmp_logs, bad_verdict) -> None:
    from ai_billing_audit.clinical_metrics import record_submit_webhook

    with pytest.raises(ValueError, match="verdict must be one of"):
        record_submit_webhook(
            clinic_id="clinic_a", encounter_id="enc_1",
            verdict=bad_verdict, findings=[],
            hmac_ok=False, latency_ms=0,
        )


# ---------------------------------------------------------------------------
# Feedback loop week (t_2ab66102)
# ---------------------------------------------------------------------------


def test_run_feedback_loop_week_empty_log_is_advisory(tmp_logs) -> None:
    """Empty feedback log → accept_rate=None, both flags False, status=advisory."""
    from ai_billing_audit.clinical_metrics import run_feedback_loop_week

    payload = run_feedback_loop_week(clinic_id="clinic_a")
    assert payload["status"] == "advisory"
    assert payload["accept_rate"] is None
    assert payload["over_flagging"] is False
    assert payload["under_flagging"] is False
    assert payload["accept_count"] == 0
    assert payload["dismiss_count"] == 0


def test_run_feedback_loop_week_handles_store_exception(tmp_logs, monkeypatch) -> None:
    """If the underlying FeedbackStore blows up, the helper still returns
    a structured payload — never propagates.
    """
    from ai_billing_audit import clinical_metrics, feedback as _feedback

    class _BoomStore:
        def read_all(self):
            raise RuntimeError("storage unavailable")

    monkeypatch.setattr(_feedback, "FeedbackStore", _BoomStore)
    payload = clinical_metrics.run_feedback_loop_week(clinic_id="clinic_a")
    assert payload["accept_rate"] is None
    assert payload["status"] == "advisory"


# ---------------------------------------------------------------------------
# Tenant rules (t_06ceaa04)
# ---------------------------------------------------------------------------


def test_add_tenant_rule_filters_disabled(tmp_logs) -> None:
    """Disabled rules do not appear in the list response."""
    from ai_billing_audit.clinical_metrics import add_tenant_rule, list_tenant_rules

    add_tenant_rule(
        "clinic_a", rule_id="no_99211", description="We don't bill 99211",
        severity="low", pattern="code==99211",
    )
    add_tenant_rule(
        "clinic_a", rule_id="chronic_modifier",
        description="Always append modifier-25 on chronic visits",
        severity="info", pattern="visit_type==chronic", enabled=False,
    )
    rules = list_tenant_rules("clinic_a")
    ids = sorted(r["rule_id"] for r in rules)
    assert ids == ["no_99211"]


def test_add_tenant_rule_duplicate_overwrites(tmp_logs) -> None:
    """Adding the same rule_id twice leaves the latest state."""
    from ai_billing_audit.clinical_metrics import add_tenant_rule, list_tenant_rules

    add_tenant_rule(
        "clinic_a", rule_id="dup", description="old",
        severity="low", pattern="x==1",
    )
    add_tenant_rule(
        "clinic_a", rule_id="dup", description="new",
        severity="low", pattern="x==2",
    )
    rules = list_tenant_rules("clinic_a")
    assert len(rules) == 1
    assert rules[0]["description"] == "new"
    assert rules[0]["pattern"] == "x==2"


@pytest.mark.parametrize("bad_severity", ["critical", "extreme", "", "LOW"])
def test_add_tenant_rule_bad_severity_raises(tmp_logs, bad_severity) -> None:
    from ai_billing_audit.clinical_metrics import add_tenant_rule

    with pytest.raises(ValueError, match="severity must be one of"):
        add_tenant_rule(
            "clinic_a", rule_id="bad",
            description="d", severity=bad_severity, pattern="p",
        )


# ---------------------------------------------------------------------------
# Onboarding wizard (t_58fbe2dd)
# ---------------------------------------------------------------------------


def test_save_onboarding_low_volume_recommends_haiku_weekly_medium(tmp_logs) -> None:
    """monthly_claim_volume=120 → haiku / weekly / medium."""
    from ai_billing_audit.clinical_metrics import save_onboarding_answers

    payload = save_onboarding_answers(
        "clinic_a", ehr="AdvancedMD",
        providers=4, billers=2, monthly_claim_volume=120,
        biggest_denial_type="modifier-25",
    )
    assert payload["recommended_default_model"] == "haiku"   # < 200
    assert payload["recommended_email_cadence"] == "weekly"  # < 500
    assert payload["recommended_severity_threshold"] == "medium"  # >= 100


def test_save_onboarding_high_volume_recommends_sonnet_daily(tmp_logs) -> None:
    """monthly_claim_volume=800 → sonnet / daily / medium."""
    from ai_billing_audit.clinical_metrics import save_onboarding_answers

    payload = save_onboarding_answers(
        "clinic_a", ehr="Epic",
        providers=12, billers=8, monthly_claim_volume=800,
        biggest_denial_type="auth",
    )
    assert payload["recommended_default_model"] == "sonnet"
    assert payload["recommended_email_cadence"] == "daily"
    assert payload["recommended_severity_threshold"] == "medium"


def test_save_onboarding_very_low_volume_uses_low_severity(tmp_logs) -> None:
    """monthly_claim_volume < 100 → severity threshold = low."""
    from ai_billing_audit.clinical_metrics import save_onboarding_answers

    payload = save_onboarding_answers(
        "clinic_a", ehr="Other",
        providers=1, billers=1, monthly_claim_volume=50,
        biggest_denial_type="",
    )
    assert payload["recommended_severity_threshold"] == "low"


def test_get_onboarding_returns_latest_or_none(tmp_logs) -> None:
    from ai_billing_audit.clinical_metrics import (
        get_onboarding,
        save_onboarding_answers,
    )

    assert get_onboarding("clinic_a") is None

    save_onboarding_answers(
        "clinic_a", ehr="AdvancedMD",
        providers=4, billers=2, monthly_claim_volume=120,
        biggest_denial_type="modifier-25",
    )
    save_onboarding_answers(
        "clinic_a", ehr="Epic",
        providers=4, billers=2, monthly_claim_volume=120,
        biggest_denial_type="auth",
    )
    out = get_onboarding("clinic_a")
    assert out is not None
    assert out["ehr"] == "Epic"  # latest wins


@pytest.mark.parametrize(
    "providers,billers,volume",
    [
        (0, 1, 1),
        (1, 0, 1),
        (1, 1, 0),
        (-1, 1, 100),
        (1, -1, 100),
    ],
)
def test_save_onboarding_non_positive_counts_raise(
    tmp_logs, providers, billers, volume,
) -> None:
    from ai_billing_audit.clinical_metrics import save_onboarding_answers

    with pytest.raises(ValueError, match="must be > 0"):
        save_onboarding_answers(
            "clinic_a", ehr="AdvancedMD",
            providers=providers, billers=billers,
            monthly_claim_volume=volume,
            biggest_denial_type="x",
        )


# ---------------------------------------------------------------------------
# Pre-submit block (t_d080595b)
# ---------------------------------------------------------------------------


def test_record_pre_submit_block_round_trip(tmp_logs) -> None:
    from ai_billing_audit.clinical_metrics import (
        list_pre_submit_blocks,
        record_pre_submit_block,
    )

    record_pre_submit_block(
        "clinic_a", encounter_id="enc_1", finding_count=3,
        blocked=True, override_reason="",
    )
    record_pre_submit_block(
        "clinic_a", encounter_id="enc_2", finding_count=2,
        blocked=True, override_reason="patient is terminal, billing is moot",
    )
    rows = list_pre_submit_blocks("clinic_a")
    assert len(rows) == 2
    assert rows[1]["override_reason"].startswith("patient")
    assert list_pre_submit_blocks("other") == []


# ---------------------------------------------------------------------------
# Browser extension audit (t_8b915264)
# ---------------------------------------------------------------------------


def test_record_extension_audit_round_trip(tmp_logs) -> None:
    from ai_billing_audit.clinical_metrics import record_extension_audit

    payload = record_extension_audit(
        clinic_id="clinic_a", ehr="athena", encounter_id="enc_1",
        findings_count=2, user_action="edited_then_submitted",
        extension_version="0.4.1",
    )
    assert payload["ehr"] == "athena"
    assert payload["user_action"] == "edited_then_submitted"
    assert payload["extension_version"] == "0.4.1"


@pytest.mark.parametrize("bad_ehr", ["bogus_ehr", "EPIC", "", "advanced"])
def test_record_extension_audit_bad_ehr_raises(tmp_logs, bad_ehr) -> None:
    from ai_billing_audit.clinical_metrics import record_extension_audit

    with pytest.raises(ValueError, match="ehr must be one of"):
        record_extension_audit(
            clinic_id="clinic_a", ehr=bad_ehr, encounter_id="enc_1",
            findings_count=0, user_action="submitted", extension_version="0.0",
        )


@pytest.mark.parametrize(
    "bad_action", ["panic_clicked", "edited", "", "SUBMITTED"],
)
def test_record_extension_audit_bad_user_action_raises(tmp_logs, bad_action) -> None:
    from ai_billing_audit.clinical_metrics import record_extension_audit

    with pytest.raises(ValueError, match="user_action must be"):
        record_extension_audit(
            clinic_id="clinic_a", ehr="athena", encounter_id="enc_1",
            findings_count=0, user_action=bad_action, extension_version="0.0",
        )


# ---------------------------------------------------------------------------
# Specialty mix (t_da44c384)
# ---------------------------------------------------------------------------


def test_compute_specialty_mix_sums_to_one(tmp_logs) -> None:
    """The mix dict's values must sum to ~1.0."""
    from ai_billing_audit.clinical_metrics import compute_specialty_mix

    encounters = ["primary_care"] * 60 + ["surgery"] * 30 + ["psych"] * 10
    payload = compute_specialty_mix(
        clinic_id="clinic_a", encounter_specialties=encounters,
    )
    assert payload["encounter_count"] == 100
    assert abs(sum(payload["specialty_mix"].values()) - 1.0) < 0.01


def test_compute_specialty_mix_dominant_ordering(tmp_logs) -> None:
    """``dominant_specialties`` is sorted by share, descending, top 3."""
    from ai_billing_audit.clinical_metrics import compute_specialty_mix

    encounters = ["primary_care"] * 60 + ["surgery"] * 30 + ["psych"] * 10
    payload = compute_specialty_mix(
        clinic_id="clinic_a", encounter_specialties=encounters,
    )
    assert payload["dominant_specialties"][0] == "primary_care"
    assert payload["dominant_specialties"][1] == "surgery"


def test_compute_specialty_mix_normalises_case(tmp_logs) -> None:
    """Inputs are lowercased + stripped before counting."""
    from ai_billing_audit.clinical_metrics import compute_specialty_mix

    payload = compute_specialty_mix(
        clinic_id="clinic_a",
        encounter_specialties=["  Primary_Care ", "PRIMARY_CARE", "primary_care"],
    )
    assert payload["specialty_mix"]["primary_care"] == 1.0


def test_compute_specialty_mix_ignores_blank_strings(tmp_logs) -> None:
    """Whitespace-only entries are skipped, not crashed on."""
    from ai_billing_audit.clinical_metrics import compute_specialty_mix

    payload = compute_specialty_mix(
        clinic_id="clinic_a",
        encounter_specialties=["", "   ", "primary_care"],
    )
    assert payload["encounter_count"] == 1


def test_compute_specialty_mix_empty_raises(tmp_logs) -> None:
    from ai_billing_audit.clinical_metrics import compute_specialty_mix

    with pytest.raises(ValueError, match="non-empty"):
        compute_specialty_mix(clinic_id="clinic_a", encounter_specialties=[])


def test_get_specialty_mix_returns_latest_or_none(tmp_logs) -> None:
    from ai_billing_audit.clinical_metrics import (
        compute_specialty_mix,
        get_specialty_mix,
    )

    assert get_specialty_mix("clinic_a") is None

    compute_specialty_mix(
        clinic_id="clinic_a", encounter_specialties=["primary_care"],
    )
    compute_specialty_mix(
        clinic_id="clinic_a", encounter_specialties=["surgery"],
    )
    payload = get_specialty_mix("clinic_a")
    assert payload is not None
    assert "surgery" in payload["specialty_mix"]

    assert get_specialty_mix("other") is None


# ---------------------------------------------------------------------------
# Bulk-accept pattern (t_f3d392b2)
# ---------------------------------------------------------------------------


def test_detect_bulk_accept_pattern_below_threshold_returns_none(tmp_logs) -> None:
    from ai_billing_audit.clinical_metrics import detect_bulk_accept_pattern

    assert detect_bulk_accept_pattern(
        "clinic_a", rule_id="mod_25", dismissal_count=5,
    ) is None


def test_detect_bulk_accept_pattern_above_threshold_persists(tmp_logs) -> None:
    from ai_billing_audit.clinical_metrics import detect_bulk_accept_pattern

    proposal = detect_bulk_accept_pattern(
        "clinic_a", rule_id="mod_25", dismissal_count=12,
    )
    assert proposal is not None
    assert proposal["opt_in"] is False
    assert proposal["clinic_id"] == "clinic_a"
    assert proposal["rule_id"] == "mod_25"
    assert proposal["dismissal_count"] == 12
    assert len(proposal["event_id"]) == 32


def test_detect_bulk_accept_pattern_custom_min_dismissals(tmp_logs) -> None:
    """The default min_dismissals=10 can be raised per call."""
    from ai_billing_audit.clinical_metrics import detect_bulk_accept_pattern

    # 12 dismissals, min_dismissals=20 → still below threshold
    assert detect_bulk_accept_pattern(
        "clinic_a", rule_id="mod_25", dismissal_count=12, min_dismissals=20,
    ) is None
    # 25 dismissals, min_dismissals=20 → proposal emitted
    proposal = detect_bulk_accept_pattern(
        "clinic_a", rule_id="mod_25", dismissal_count=25, min_dismissals=20,
    )
    assert proposal is not None


def test_opt_in_bulk_accept_round_trip(tmp_logs) -> None:
    from ai_billing_audit.clinical_metrics import (
        detect_bulk_accept_pattern,
        opt_in_bulk_accept,
    )

    proposal = detect_bulk_accept_pattern(
        "clinic_a", rule_id="mod_25", dismissal_count=12,
    )
    assert proposal is not None
    pattern_id = proposal["event_id"]

    opted = opt_in_bulk_accept(pattern_id, actor="biller_1")
    assert opted["opt_in"] is True
    assert opted["opt_in_actor"] == "biller_1"
    assert "opt_in_at" in opted


def test_opt_in_bulk_accept_unknown_pattern_raises(tmp_logs) -> None:
    from ai_billing_audit.clinical_metrics import opt_in_bulk_accept

    with pytest.raises(ValueError, match="not found"):
        opt_in_bulk_accept("nonexistent_id")


# ---------------------------------------------------------------------------
# Doctor positive feedback digest (t_585dcaed)
# ---------------------------------------------------------------------------


def test_queue_doctor_positive_digest_round_trip(tmp_logs) -> None:
    from ai_billing_audit.clinical_metrics import (
        list_doctor_positive_digests,
        queue_doctor_positive_digest,
    )

    payload = queue_doctor_positive_digest(
        "doc_1", "clinic_a", week_of="2026-W26",
        notes_written=47, notes_clean=45, notes_with_quick_fix=2,
        estimated_savings_usd=9200.0,
    )
    assert payload["status"] == "queued"
    assert payload["notes_clean"] == 45
    assert payload["week_of"] == "2026-W26"

    digests = list_doctor_positive_digests("doc_1")
    assert len(digests) == 1
    assert digests[0]["clinic_id"] == "clinic_a"
    # Other doctor: isolation
    assert list_doctor_positive_digests("other_doc") == []