"""Generate a seed-distinct 50-encounter held-out test split.

The optimizer's val split is generated by
``ai_billing_audit.ground_truth._split_data(train_seed=1729,
train_n=100, val_n=50)`` and the val encounters are written to
``data/val.json`` with id offsets enc_10000..enc_10049. This script
generates a fresh 50-encounter holdout using a *different* train_seed
and an id offset that does not collide with the existing train (enc_0000..enc_0099)
or val (enc_10000..enc_10049) splits. The default output is
``data/holdout_seed{SEED}.json`` with id range enc_{OFFSET}..enc_{OFFSET+49}.

The seed is fully documented in the output JSON's ``train_seed`` field
so the run can be reproduced byte-for-byte.

Usage:
    python scripts/generate_holdout.py --seed 9999 --out data/holdout_seed9999.json
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = PROJECT_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from ai_billing_audit.ground_truth import (  # noqa: E402
    _split_data,
    ground_truth_for,
    _build_encounter,
)
import random  # noqa: E402


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    p.add_argument("--seed", type=int, default=9999,
                   help="Distinct from the optimizer's 1729 (default: 9999).")
    p.add_argument("--n", type=int, default=50,
                   help="Number of holdout encounters to generate (default: 50).")
    p.add_argument("--offset", type=int, default=20000,
                   help="Encounter-id offset; default 20000 avoids collision with "
                        "train enc_0000..0099 and val enc_10000..10049.")
    p.add_argument("--out", type=Path,
                   default=PROJECT_ROOT / "data" / "holdout_seed9999.json")
    p.add_argument("--n-train", type=int, default=100,
                   help="Dummy train_n passed to _split_data; only val_n matters here.")
    args = p.parse_args()

    if args.seed == 1729:
        print("ERROR: --seed must differ from the optimizer's 1729",
              file=sys.stderr)
        return 2

    # _split_data builds train and val together. We re-build the val side
    # standalone so we control the offset and skip the train side.
    rng = random.Random(args.seed + 1)
    from ai_billing_audit.ground_truth import _TEMPLATES  # noqa: PLC0415

    encounters = []
    for i in range(args.n):
        tmpl_idx = (args.offset + i) % len(_TEMPLATES)
        is_flagged, note, rule_ids = _TEMPLATES[tmpl_idx]
        if rng.random() < 0.15 and len(rule_ids) > 1:
            drop = rng.randrange(len(rule_ids) - 1)
            rule_ids = rule_ids[:drop] + rule_ids[drop + 1:]
        enc = _build_encounter(args.offset + i, is_flagged, note, rule_ids)
        enc["ground_truth"] = ground_truth_for(enc)
        encounters.append(enc)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(encounters, indent=2, ensure_ascii=False))

    sha = "sha256:" + hashlib.sha256(args.out.read_bytes()).hexdigest()
    n_flagged = sum(1 for e in encounters if e.get("is_flagged"))
    n_clean = len(encounters) - n_flagged
    n_findings = sum(len(e["ground_truth"]) for e in encounters)
    meta = {
        "holdout_path": str(args.out),
        "holdout_sha256": sha,
        "train_seed": args.seed,
        "size": len(encounters),
        "n_flagged": n_flagged,
        "n_clean": n_clean,
        "n_gold_findings": n_findings,
        "encounter_id_range": [
            encounters[0]["encounter_id"], encounters[-1]["encounter_id"]
        ],
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "generator": "scripts/generate_holdout.py",
        "notes": (
            f"Seed-distinct 50-encounter holdout for overfit test "
            f"(kanban t_c6838361). train_seed={args.seed} differs from "
            f"the optimizer's 1729. Encounter-id range "
            f"{encounters[0]['encounter_id']}..{encounters[-1]['encounter_id']} "
            f"is disjoint from train (enc_0000..enc_0099) and val "
            f"(enc_10000..enc_10049). Reproducible: re-run this script "
            f"with the same --seed and --offset to get a byte-identical file."
        ),
    }
    meta_path = args.out.with_suffix(args.out.suffix + ".meta.json")
    meta_path.write_text(json.dumps(meta, indent=2) + "\n")

    print(
        f"wrote {len(encounters)} encounters ({n_flagged} flagged, "
        f"{n_clean} clean, {n_findings} gold findings) to {args.out} "
        f"[seed={args.seed}, offset={args.offset}, sha={sha}]"
    )
    print(f"wrote metadata to {meta_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
