import type { Metadata } from "next"; import Link from "next/link";
import { requirePlatformPage } from "@/lib/platform-auth"; import { hasPlatformCapability } from "@/lib/platform-capabilities"; import { loadHqMarketingRegistry } from "@/lib/hq-data";
import { HqNav } from "../hq-nav"; import styles from "../hq.module.css"; import { RegistryCreator } from "./registry-creator";
export const metadata: Metadata = { robots: { index: false, follow: false } }; export const dynamic = "force-dynamic"; export const runtime = "nodejs";
function surfaces(value: string) { try { const parsed = JSON.parse(value) as unknown; return Array.isArray(parsed) ? parsed.join(", ") : "None"; } catch { return "Invalid registry value"; } }
export default async function MarketingPage() { const operator = await requirePlatformPage("marketing:read", "hq_marketing"); const registry = await loadHqMarketingRegistry(); const canWrite = hasPlatformCapability(operator.role, true, "marketing:write"); const owners = registry.owners.map((owner) => ({ userId: owner.userId, role: owner.role, label: owner.user.name ?? owner.user.email }));
  return <main id="main" className={styles.shell}><HqNav /><span className={styles.eyebrow}>Claim and content governance · {operator.role}</span><h1 className={styles.heading}>Marketing registry</h1><p className={styles.subheading}>Evidence, permission, surface approval, and content review. Registry actions never publish, send, spend, or change pricing.</p>{canWrite ? <section className={styles.section}><RegistryCreator claims={registry.claims.map((claim) => ({ id: claim.id, label: claim.exactClaim.slice(0, 70), status: claim.status }))} owners={owners} /></section> : null}
  <section className={styles.section}><h2>Claims</h2>{registry.claims.length ? <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Exact claim</th><th>Evidence</th><th>Status</th><th>Allowed surfaces</th><th>Review</th></tr></thead><tbody>{registry.claims.map((claim) => <tr key={claim.id}><td><Link className={styles.navLink} href={`/hq/marketing/claim/${claim.id}`}>{claim.exactClaim}</Link></td><td>{claim.evidenceType.replaceAll("_", " ")}</td><td>{claim.status}</td><td>{surfaces(claim.allowedSurfacesJson)}</td><td>{claim.reviewAt?.toLocaleDateString("en-CA") ?? "Not set"}</td></tr>)}</tbody></table></div> : <div className={styles.empty}>No registered claims.</div>}</section>
  <section className={styles.section}><h2>Content assets</h2>{registry.assets.length ? <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Asset</th><th>Segment</th><th>Channel</th><th>Status</th><th>Claim</th></tr></thead><tbody>{registry.assets.map((asset) => <tr key={asset.id}><td><Link className={styles.navLink} href={`/hq/marketing/asset/${asset.id}`}>{asset.title}</Link></td><td>{asset.targetSegment}</td><td>{asset.channel}</td><td>{asset.status}</td><td>{asset.claimApproval ? `${asset.claimApproval.status}: ${asset.claimApproval.exactClaim.slice(0, 50)}` : asset.containsMarketingClaim ? "Missing" : "No claim"}</td></tr>)}</tbody></table></div> : <div className={styles.empty}>No content assets.</div>}</section></main>;
}
