"use client";
import { useState, type FormEvent } from "react"; import { useRouter } from "next/navigation";
import { CLAIM_EVIDENCE_TYPES, CONTENT_ASSET_TYPES, CONTENT_CHANNELS, MARKETING_SURFACES } from "@/lib/marketing-rules"; import styles from "../hq.module.css";
interface Claim { id: string; label: string; status: string } interface Owner { userId: string; role: string; label: string }
export function RegistryCreator({ claims, owners }: { claims: Claim[]; owners: Owner[] }) { const router = useRouter(); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  async function send(path: string, body: Record<string, unknown>) { setBusy(true); setMessage(null); try { const response = await fetch(path, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ mutationId: crypto.randomUUID(), ...body }) }); const payload = await response.json() as { detail?: string; error?: string }; if (!response.ok) { setMessage(payload.detail ?? payload.error ?? "Could not save record."); return; } setMessage("Draft recorded. Nothing was published."); router.refresh(); } catch { setMessage("Network error. No record was confirmed."); } finally { setBusy(false); } }
  function claimSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); void send("/api/hq/marketing/claims", { exactClaim: data.get("exactClaim"), evidenceType: data.get("evidenceType"), evidenceReference: String(data.get("evidenceReference") || "") || null, customerPermissionReference: String(data.get("customerPermissionReference") || "") || null, allowedSurfaces: data.getAll("allowedSurfaces"), reviewAt: null, expiresAt: null, replacesClaimId: null }); }
  function assetSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); void send("/api/hq/marketing/assets", { title: data.get("title"), assetType: data.get("assetType"), targetSegment: data.get("targetSegment"), channel: data.get("channel"), containsMarketingClaim: data.get("containsMarketingClaim") === "on", claimApprovalId: String(data.get("claimApprovalId") || "") || null, artifactReference: String(data.get("artifactReference") || "") || null, ownerUserId: String(data.get("ownerUserId") || "") || null, plannedAt: null, reviewAt: null }); }
  return <div className={styles.detailGrid}>{message ? <div role="status" className={styles.success}>{message}</div> : null}<form className={`${styles.form} ${styles.card}`} onSubmit={claimSubmit}><h2>Register claim draft</h2><p className={styles.muted}>Exact wording and evidence only. Drafts cannot be used publicly.</p><label className={styles.field}>Exact claim<textarea name="exactClaim" className={styles.textarea} required minLength={5} maxLength={500} /></label><label className={styles.field}>Evidence type<select name="evidenceType" className={styles.select}>{CLAIM_EVIDENCE_TYPES.map((v) => <option key={v} value={v}>{v.replaceAll("_", " ")}</option>)}</select></label><label className={styles.field}>Evidence reference<input name="evidenceReference" className={styles.input} maxLength={240} /></label><label className={styles.field}>Customer permission reference<input name="customerPermissionReference" className={styles.input} maxLength={240} /></label><fieldset className={styles.form}><legend>Requested surfaces</legend>{MARKETING_SURFACES.map((v) => <label className={styles.checkbox} key={v}><input type="checkbox" name="allowedSurfaces" value={v} />{v}</label>)}</fieldset><button className={styles.button} disabled={busy}>Record draft</button></form>
  <form className={`${styles.form} ${styles.card}`} onSubmit={assetSubmit}><h2>Register content draft</h2><p className={styles.muted}>This schedules no publication and sends no message.</p><label className={styles.field}>Title<input name="title" className={styles.input} required minLength={3} maxLength={160} /></label><label className={styles.field}>Asset type<select name="assetType" className={styles.select}>{CONTENT_ASSET_TYPES.map((v) => <option key={v} value={v}>{v.replaceAll("_", " ")}</option>)}</select></label><label className={styles.field}>Target segment<input name="targetSegment" className={styles.input} required minLength={3} maxLength={160} /></label><label className={styles.field}>Channel<select name="channel" className={styles.select}>{CONTENT_CHANNELS.map((v) => <option key={v} value={v}>{v}</option>)}</select></label><label className={styles.checkbox}><input type="checkbox" name="containsMarketingClaim" />Contains a marketing claim</label><label className={styles.field}>Linked approved claim<select name="claimApprovalId" className={styles.select}><option value="">None</option>{claims.map((claim) => <option key={claim.id} value={claim.id}>{claim.label} · {claim.status}</option>)}</select></label><label className={styles.field}>Artifact reference<input name="artifactReference" className={styles.input} maxLength={240} /></label><label className={styles.field}>Owner<select name="ownerUserId" className={styles.select}><option value="">Unassigned</option>{owners.map((owner) => <option key={owner.userId} value={owner.userId}>{owner.label} · {owner.role}</option>)}</select></label><button className={styles.button} disabled={busy}>Record draft</button></form></div>;
}
